### ISSUE TITLE
Solutions for 6.2.1 and 6.3.1 are identical.

### ISSUE THREAD

**Issue by jnbrewster** [GA-WDI/fundamentals#105]
Hello,

The "Associative Arrays" exercise and the "Iterating over Arrays" exercise solutions are the same.
https://github.com/generalassembly-studio/fundamentals/blob/master/exercise-solutions.md

Regards,

Joel

**Comment by jeannyvaidya** [comment]
@jnbrewster good catch! Updated the solutions file.
