### ISSUE TITLE
re: v3.0 video is already supported w/ gitbook platform

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#108]
http://ga-dc.github.io/fundamentals/v2.9.9/00_chapter/get_started.html

https://github.com/ga-dc/fundamentals/commit/c74c19df7761ca3ad51012b67e125402d1efed16

**Comment by jessicaGA** [comment]
Thanks @jshawl we figured that out. We've added quite a few videos to the new version. We will share by tomorrow. Still dealing with some build issues.
