### ISSUE TITLE
password protect /v3.0/

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#109]

**Comment by code-for-coffee** [comment]
@jshawl - https://github.com/GA-WDI/fundamentals-v3.0/issues/25

**Comment by jeannyvaidya** [comment]
@jshawl @jessicaGA @code-for-coffee closing. It doesn't seem like this is going to be implemented for v3.0 but when we do move/update in future to the new pre-work app, we'll keep this in consideration.
