### ISSUE TITLE
Unit 6 quiz references .map method, not yet explained

### ISSUE THREAD

**Issue by mnorelli** [GA-WDI/fundamentals#126]
In a previous version of Unit 6, the .map and .forEach array methods were discussed.  With recent changes, these methods no longer appear in the Unit 6 discussion.

So when question 9 in the Unit 6 quiz appears:
![](https://d4z6dx8qrln4r.cloudfront.net/image-5553c0e4b4535-default.png)
students have not yet been exposed to the method in the *return* statement.

(Though given the other multichoice answers and *return* statement logic, it's not too hard to figure out the correct answer.)

**Comment by jeannyvaidya** [comment]
@mnorelli thanks for catch! Leaving it in for now, because if I delete the question, all previous student data for this question would be deleted too. We're switching over to Fundamentals v3.0 in June and I've fixed the issue for the new version.
