### ISSUE TITLE
Dot accessor question without explanation in Fundamentals Quiz #6

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#128]
Quiz #6, question #12 is confusing.  It insists that the answer involve assigning a value from an object using a "dot accessor" (e.g. myObject.property) rather than with square brackets (e.g. myObject["property"]).  While I agree that the former method is better stylistically, the course material itself _never mentions it_, only the latter method.  I think somebody can fix this pretty easily by adding a note at the end of the 6.3 Associative Arrays section."

**Comment by jeannyvaidya** [comment]
@ZebGirouard thanks for pointing this out. I'll instead change the answers to square brackets so we can leave out the dot accessor.
