### ISSUE TITLE
100% Scores Go To Try Again Screen 

### ISSUE THREAD

**Issue by jessicaGA** [GA-WDI/fundamentals#132]
If a student scores 100% the last screen is always "try again". Is there a way we can send them to a Good Job screen instead? 

![pasted image at 2016_05_19 11_44 am](https://cloud.githubusercontent.com/assets/3017970/15430679/66c6a314-1e74-11e6-837e-9be4a910b8e6.png)

**Comment by jeannyvaidya** [comment]
@jessicaGA closing this issue since there's a duplicate.
