### ISSUE TITLE
Solution link key is incorrect

### ISSUE THREAD

**Issue by johnapaolino** [GA-WDI/fundamentals#134]
In this page there is a link to solutions: [Chapter 8, exercise 3](http://fundamentals.generalassemb.ly/v3.0/08_chapter/03_exercise.html), but the key doesn't match the solution page: [Solutions](https://github.com/generalassembly-studio/fundamentals/blob/master/exercise-solutions.md)

**Comment by jeannyvaidya** [comment]
@johnapaolino thanks for catching this. Fixed the link to proper solution page: https://github.com/GA-WDI/fundamentals/blob/v3.0/08_chapter/03_exercise.md
