### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by johnapaolino** [GA-WDI/fundamentals#135]
Link at the bottom of the page for [chapter 9](http://fundamentals.generalassemb.ly/v3.0/09_chapter/09_assessment.htmll) says "Next up: Chapter 5"

**Comment by jeannyvaidya** [comment]
@johnapaolino fixed. Thanks for catching that!

https://github.com/GA-WDI/fundamentals/commit/28f02c00329fb561812759c7caea45090a59e454
