### ISSUE TITLE
Backlog 

### ISSUE THREAD

**Issue by jeannyvaidya** [GA-WDI/fundamentals#136]

**Comment by jeannyvaidya** [comment]
Windows Bash vs OS X Bash warning: https://github.com/GA-WDI/fundamentals/issues/119

code-for-coffee commented 22 hours ago

The differences between Windows Bash CLI commands maybe should be denoted with a warning or some windows icon to let students know. I find it a little confusing when I see some of them back to back. Example would be 06_chapter/08_lesson.md where there’s open and write depending on the OS.

It would be cool if we could have a Windows icon/banner to let students know about Windows specific code.

**Comment by jeannyvaidya** [comment]
Unit 10 Adding Diagram: https://github.com/GA-WDI/fundamentals/issues/120

@code-for-coffee opened this issue 22 hours ago · 0 comments

Inside of `10_chapter/02_lesson.html` for Unit 8, function expressions are discussed with their different parts. I feel like after the word-heavy explanation on the unit beforehand that it would be beneficial to include a diagram to points of **parameters** and other parts of a function expression.

Something similar to this... but nowhere near as complex?

![https://www.safaribooksonline.com/library/view/head-first-html5/9781449314712/httpatomoreillycomsourceoreillyimages1345239.png.jpg](https://www.safaribooksonline.com/library/view/head-first-html5/9781449314712/httpatomoreillycomsourceoreillyimages1345239.png.jpg)

**Comment by jeannyvaidya** [comment]
"Try Again" message in quiz when 100% achieved: https://github.com/GA-WDI/fundamentals/issues/133

- Changed to "Redo Quiz" but Typeform does not allow for conditional option for message if 100% achieved.

**Comment by jeannyvaidya** [comment]
jeannyvaidya commented on Apr 13

Create proper folders for asset files in elkfolder and rename/move current chapter folders for assets to match new format of Fundamentals

https://github.com/GA-WDI/fundamentals/issues/112

**Comment by microsarah** [comment]
@jnappy @jessicaGA is this something I should work on?

**Comment by jnappy** [comment]
@microsarah im going to close this one - don't worry about it
