### ISSUE TITLE
Further Reading Sections in Videos

### ISSUE THREAD

**Issue by jeannyvaidya** [GA-WDI/fundamentals#139]
From Producer: 

I had a student who replied with this about the further readings: "A few of the videos in units 1-4 mention to learn more in the further reading.

I did notice further reading links (that were actually included) at the end of 5.2, but 5.1 says I need a link for reset.css that is included in further reading, and I'm guessing I'll need for the unit 5 assignment.

**Comment by jnappy** [comment]
@jessicaGA im having trouble figuring out what this means - do you know what she's referring to?

**Comment by jessicaGA** [comment]
We are using Circuits videos and some of them mention a further reading section. That section doesn't exist in Fundamentals

**Comment by microsarah** [comment]
Progress here: https://generalassembly.atlassian.net/browse/EPM-770

**Comment by microsarah** [comment]
@jnappy you merged my changes for units 1-5 where I added further reading when needed. Can we close this?

**Comment by jessicaGA** [comment]
This is done pending merge.

**Comment by jnappy** [comment]
Done!
