### ISSUE TITLE
Exercise 3.3.2 (boolean logic) is confusing

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#14]
Per student feedback in the `#wdi-fundamentals` channel, Exercise 3.3.2 is rather confusing. I tend to agree. Boolean logic is really tricky and I think we need to really rethink this exercise.

**Comment by jeannyvaidya** [comment]
Closing issue as per @code-for-coffee update (Exercise 3.3.2 (boolean logic) update #67).
