### ISSUE TITLE
Improperly displayed `<h3>` tag code in "Elements, Elements, Elements!"

### ISSUE THREAD

**Issue by bgveenstra** [GA-WDI/fundamentals#140]
In the "Elements, Elements, Elements" lesson ([chapter 2 lesson 2](http://fundamentals.generalassemb.ly/02_chapter/02_lesson.html)), the "Checkpoint" section's first bullet asks "Which heading tag is larger? `<h3` or `<h6>`?"  

The first tag should be `<h3>` (with the closing angle bracket).  

Screenshot: 

<img width="370" alt="unclosed h3 tag typo in elements elements elements" src="https://cloud.githubusercontent.com/assets/3254910/16815976/04d5f7d4-48f1-11e6-81ab-25d959c00654.png">

**Comment by jeannyvaidya** [comment]
@bgveenstra thanks for this catch! Fixed here: https://github.com/GA-WDI/fundamentals/commit/25f16721a449a4ca207c33b77b6330106ebf503e
