### ISSUE TITLE
Conflicting instructions in Chapter 2, section 03_exercise.

### ISSUE THREAD

**Issue by bgveenstra** [GA-WDI/fundamentals#141]
In chapter 2's section 3_exercise "Your Turn" ([link](http://fundamentals.generalassemb.ly/02_chapter/03_exercise.html)), the instructions in the JSBin do not match the example or instructions in the markdown portion of the page.  

The JSBin HTML has a comment saying both the second and third lines should be in `p` tags, while step 4 of the instructions below says that the second line should be in an `h2` tag. An `h2` is also used in the example output at the top of the page and the "Checkpoint" section at the bottom.

Consider changing the comment in the JSBin so that it also instructs students to use `h2`. 

Screenshots:
<img width="432" alt="jsbin instructions with p tag" src="https://cloud.githubusercontent.com/assets/3254910/16816382/7a3b8790-48f2-11e6-9d34-ff776d1945bd.png">

<img width="548" alt="markdown instruction asking for h2" src="https://cloud.githubusercontent.com/assets/3254910/16816405/97faa5e0-48f2-11e6-9871-d1b69d75227d.png">

**Comment by jeannyvaidya** [comment]
@bgveenstra thanks so much for pointing out the inconsistency. Fixed it in the JSBIN instructions. Here's my commit for the new embed: https://github.com/GA-WDI/fundamentals/commit/f73d6652f458809e8770c881d1b47a45aaf5b008

It will show up properly in the gitbook.
