### ISSUE TITLE
Partial missing question text in section 2.3 quiz, question 9.

### ISSUE THREAD

**Issue by bgveenstra** [GA-WDI/fundamentals#142]
It looks like `<!DOCTYPE html>` didn't render as expected in question 9 of the section 2.3 quiz ([link](http://fundamentals.generalassemb.ly/02_chapter/06_quiz.html)), as the question reads "What does `` indicate?".

It's pretty easy with context to tell that the question is asking about the DOCTYPE tag.  Check formatting or reword question for extra clarity.

<img width="707" alt="screen shot 2016-07-13 at 12 21 52 pm" src="https://cloud.githubusercontent.com/assets/3254910/16816814/aaa0db86-48f4-11e6-917c-2b9a0a1a0ba0.png">

**Comment by jeannyvaidya** [comment]
@bgveenstra unfortunately I wasn't able to get it to render in the quiz at all. I reworded the question to: What does the Document Type Declaration or DOCTYPE indicate?

http://fundamentals.generalassemb.ly/02_chapter/06_quiz.html

Thanks!
