### ISSUE TITLE
Unintended "sss" in JSBin in chapter 4 section 04_exercise?

### ISSUE THREAD

**Issue by bgveenstra** [GA-WDI/fundamentals#143]
There are 3 `s`s after the `</html>` tag in the JSBin HTML for the  quote layout/styling exercise in chapter 4's section 04_exercise ([link](http://fundamentals.generalassemb.ly/04_chapter/04_exercise.html)).  

Based on context including the expected output image near the top of the markdown for this page, it looks like these `s`s may have been added accidentally.

Partial Screenshot of JSBin:

<img width="775" alt="screen shot 2016-07-13 at 3 33 32 pm" src="https://cloud.githubusercontent.com/assets/3254910/16822187/a1a36bdc-490f-11e6-8d4f-150c0a376108.png">

**Comment by jeannyvaidya** [comment]
@bgveenstra I deleted the 'sss' looks like it was a typo. Should be updated now. 

Thanks!
