### ISSUE TITLE
Playing Cards Image Broken

### ISSUE THREAD

**Issue by jeannyvaidya** [GA-WDI/fundamentals#145]
Student is having issues with Unit 11:
"I noticed in the Unit 11 Assignment that the link to the Bicycle Playing cards is broken(images on flip cards). Is there another link you would like us to use?"

**Comment by jnappy** [comment]
i will replace dead links with links to pixabay links: 

- https://pixabay.com/en/photos/?image_type=&cat=&min_width=&min_height=&q=playing+cards+king+&order=popular
- https://pixabay.com/en/photos/?image_type=&cat=&min_width=&min_height=&q=playing+cards+ace+&order=popular

**Comment by jnappy** [comment]
l
