### ISSUE TITLE
Code block image content in 3.9 

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#146]
The prompt indicates there should be one parent `<div>` containing several  `<div>` children. That is not what is shown in the image.

![image](https://cloud.githubusercontent.com/assets/3653013/17029690/287a9ec0-4f3a-11e6-9581-2764b43b86a8.png)

It should be 

```html
<body>
...
<div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
</div>
...
</body>
```

@jeannyvaidya, I can't add a "bug fix" label to this issue - can you please do that?

**Comment by jnappy** [comment]
thanks @GA-MEB will address this week
