### ISSUE TITLE
ternary solution is wrong

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#151]
https://github.com/generalassembly-studio/fundamentals/blob/master/exercise-solutions.md

The ternary solution shown in the answers is *not correct*. It will fail the use case where the first variable is larger than the second, but the third is larger than both the first and the second.  the solution was: *_return (a > b)? a : ((b > c)? b : c);_*

**Comment by jnappy** [comment]
@jshawl do you have a correct solution?

**Comment by sarah-ga** [comment]
I think we should remove these comments from the solution. Nesting ternary statements isn't the best practice because it makes the code difficult to read/maintain.

**Comment by jnappy** [comment]
Agreed - doesn't read well as is.  Sarah do you have a solution to @jshawl 's issue above?

**Comment by microsarah** [comment]
I wrote a comment yesterday from my GA account: 

I think we should remove these comments from the solution. Nesting ternary statements isn't the best practice because it makes the code difficult to read/maintain.

**Comment by jnappy** [comment]
ah i misread this entire thread - apologies @jshawl, @microsarah
