### ISSUE TITLE
html example missing id, breaks javascript example

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#152]
http://fundamentals.generalassemb.ly/10_chapter/10_lesson.html

**Comment by jnappy** [comment]
@jshawl could you point out what element and the corresponding ID it should have?

**Comment by mcalthrop** [comment]
I recently helped a WDI fundamentals student sort this out.

The JS example on the page looks like this:

``` js
// First, let's find the email input field.
var emailInputField = document.getElementById('email');
```

However, when you look at the HTML markup that the JS references, there is no element that has an `id` attribute with value `"email"`.

So from what I can see, the following code:

``` js
<input type="email" placeholder="Email Address">
```

needs to be replaced with something like this:

``` js
<input id="email" type="email" placeholder="Email Address">
```

**Comment by microsarah** [comment]
Looks like we have a fix @jnappy just need to merge.

**Comment by jnappy** [comment]
thanks @microsarah and @mcalthrop!
