### ISSUE TITLE
nobody in the history of javascript has ever called {} an associative array

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#154]
http://stackoverflow.com/a/8067675/850825

https://github.com/GA-WDI/fundamentals/search?utf8=%E2%9C%93&q=associative+array&type=Code

It is doing the students a disservice and not preparing them for "object" as terminology we use in class

**Comment by jnappy** [comment]
@jshawl agreed - these look like they require some re-writing.  I wonder if the intention was to expose students to the term as a fundamental across languages

btw, in the future, please try to title issues constructively 

+ @jessicaGA - i think we should prioritize for an upcoming sprint

**Comment by GA-MEB** [comment]
@jshawl You're right, and I'm the one who chose to use that name in the first place. At the time, the team that was managing Fundamentals decided that, although objects needed to be taught, we couldn't use the word "object"...  

I ultimately chose the term "associative array" over "dictionary" or "hash" so students would think of both objects and arrays as collections, but having now seen many classes go through that tutorial, I think it added a significant amount of confusion (for no apparent reason).

We should just call them objects.

**Comment by jnappy** [comment]
See https://github.com/GA-WDI/fundamentals/pull/162
