### ISSUE TITLE
Chapter 4 Lesson 6

### ISSUE THREAD

**Issue by mattmjohnson4** [GA-WDI/fundamentals#155]
nder the explanation for <main>, instead of having <header> and <footer> displayed as text, they are instead embedded in the page as elements. Buggy code as follows:

<li>These elements contain all the primary content — articles, blog posts, images, videos, etc. — between the <div data-element="head" er=""> and <footer>.</footer></div></li>

**Comment by mcalthrop** [comment]
I noticed this too.

I think this is a "feature" of gitbooks whereby using backquotes to denote code does not work – you have to enclose the relevant code in `<code>` tags.

**Comment by mcalthrop** [comment]
For reference, here's the page in question:
http://fundamentals.generalassemb.ly/04_chapter/06_lesson.html

**Comment by mcalthrop** [comment]
Actually, it turns out I was incorrect in my previous comment re. having to use `<code>` tags... all that is needed is to insert missing back-quotes.
