### ISSUE TITLE
Chapter 10 quiz has two identical answers

### ISSUE THREAD

**Issue by mattmjohnson4** [GA-WDI/fundamentals#157]
![screenshot 2016-09-08 14 27 43](https://cloud.githubusercontent.com/assets/16109674/18337040/758d402a-75d0-11e6-98bb-b2349b8e8439.png)

**Comment by microsarah** [comment]
Fixed @jnappy

**Comment by jnappy** [comment]
@mattmjohnson4 : 

![image](https://cloud.githubusercontent.com/assets/7819607/18599556/156b324e-7c27-11e6-950f-83846efb3470.png)
