### ISSUE TITLE
5.1.1 solution incorrect

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#161]
https://github.com/generalassembly-studio/fundamentals/blob/master/exercise-solutions.md

```js
var threeIfNull = function(num){
  return num || 3;
};
```

should be 

```js
var threeIfNull = function(num){
  if(num===null) return 3
  return num
};
```

reason is http://eval.js.org/#/114/0

**Comment by microsarah** [comment]
Fixed– pending merge
