### ISSUE TITLE
Typo fix for WDI pre-work Unit 10.3 (Refers to Unit 6 should be Unit 11)

### ISSUE THREAD

**Issue by mattmjohnson4** [GA-WDI/fundamentals#167]
Unit 10.3 ...

Working with NodeLists

Any time there is even the potential for a method to return more than one element, such as with getElementsByClassName(), getElementsByTagName(), and querySelectorAll, a NodeList will be returned, even if only one element is found that matches the query.

These NodeLists are collections that are numbered similar to the arrays we will be looking at in **# Unit 6.**

**Comment by microsarah** [comment]
Fixed– pending merge
