### ISSUE TITLE
Unit 4.4 seems like tags are missing from the <main> description

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#169]
<img width="1011" alt="screen shot 2016-09-26 at 11 29 37 am" src="https://cloud.githubusercontent.com/assets/12179055/18840444/9d8c6d5c-83dc-11e6-8056-9be4ae3514ac.png">

**Comment by microsarah** [comment]
I don't see any errors here in the code. @jnappy any ideas why this isn't rendering properly?
![screen shot 2016-09-28 at 1 49 32 pm](https://cloud.githubusercontent.com/assets/451523/18925567/71a6652e-8582-11e6-9115-cd3fc24788dd.png)

**Comment by jnappy** [comment]
these who up just fine on my browser: 

![image](https://cloud.githubusercontent.com/assets/7819607/19088769/bc5c73fc-8a45-11e6-954f-4babaafdd301.png)


(this is live)

@kristynrb @microsarah

**Comment by kristynrb** [comment]
I'm still missing the '<header>' and '<footer>' tags in my view. I'm looking at:
http://fundamentals.generalassemb.ly/v3.0/04_chapter/06_lesson.html

![screen shot 2016-10-04 at 4 59 06 pm](https://cloud.githubusercontent.com/assets/12179055/19092257/d7d7347e-8a53-11e6-8ad7-d1fc45a65020.png)

**Comment by jshawl** [comment]
someone removed the 3.0 branch, which means the URL will 404 on the next deploy - fixed in http://fundamentals.generalassemb.ly/04_chapter/06_lesson.html @kristynrb

**Comment by kristynrb** [comment]
Hi Jesse,

Just to confirm: the link to the fundamentals with the "v03" will no longer
be working on the next deploy?

I just want to make sure that my students have a working links while
they're completing their work for this cohort.

Thanks,
Kristyn
