### ISSUE TITLE
4.4.1 Exercise number 7 should say "border-bottom" (not "bottom-border")

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#170]
<img width="1005" alt="screen shot 2016-09-26 at 11 31 32 am" src="https://cloud.githubusercontent.com/assets/12179055/18840522/da71ca1e-83dc-11e6-8a0c-33f32429e1d6.png">

**Comment by microsarah** [comment]
Fixed– pending merge
