### ISSUE TITLE
3.1 RGB formatting example incorrect

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#171]
The letters "rgb" are missing in front of (255,0,0).

```
p {
     color: (255,0,0);
}
```

<img width="1009" alt="screen shot 2016-09-26 at 11 39 06 am" src="https://cloud.githubusercontent.com/assets/12179055/18840860/f9370210-83dd-11e6-966f-0e55d502873b.png">

**Comment by microsarah** [comment]
Fixed– pending merge
