### ISSUE TITLE
3.9 Exercise has incorrect example and formatting is off

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#172]
In this exercise, step 2 is inline with step 1. That should be on its own line. 

In step 2, it says "create five divs like so:", but lists 6 divs in the example.  I think that the first div is probably not supposed to be closed on the first line. Also, that last div should probably just be the closing div tag for the first div.

<img width="1011" alt="screen shot 2016-09-26 at 11 45 23 am" src="https://cloud.githubusercontent.com/assets/12179055/18841229/0ae02662-83df-11e6-98d8-7cc67760b2f1.png">

**Comment by microsarah** [comment]
Fixed– pending merge
