### ISSUE TITLE
5.7 Assignment - directions do not move cards as intended

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#176]
The instructions given to adjust the board do not move the cards intended. The result after following the instructions are pictured below and do not match the expected outcome image. The cards are still lined vertically.

![5 7](https://cloud.githubusercontent.com/assets/12179055/19004018/a0e092f6-8721-11e6-99d3-54df700fb28f.png)

**Comment by microsarah** [comment]
This works @kristynrb ––>  3) Add a float of left and a margin of 8% to your "card" div.

But maybe we should re-word to say "class" instead of "div." Thoughts?

**Comment by kristynrb** [comment]
@microsarah Yes, maybe: "Add a float of left and a margin of 8% to the divs that have a class of 'card'".
