### ISSUE TITLE
5.4.1 Exercise - border-bottom-color

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#178]
Step 15 says `border-bottom-color` and should just be `border-bottom`. Also, the instructions in this step with the `border-bottom` conflict with the current color of the h1 and h2 that we set earlier of 4px solid black. So, maybe mention this in the step that we're adjusting / changing the current color.

![5 4 1](https://cloud.githubusercontent.com/assets/12179055/19004240/ebe0ae20-8722-11e6-9cba-c36ecb2e929e.png)

**Comment by jshawl** [comment]
@microsarah PR has not been merged yet y u close

**Comment by microsarah** [comment]
My bad @jshawl
