### ISSUE TITLE
5.3.1 Exercise - font size

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#179]
The font size of 1.8em makes the font much larger than the font shown in the mockup. If you make the font .8em, it looks like the wireframe. Here's a sample of what it looks like with 1.8 em:

![5 3 1](https://cloud.githubusercontent.com/assets/12179055/19004298/4625bede-8723-11e6-8243-7f4dad20ad9b.png)

**Comment by microsarah** [comment]
Fixed this in issue #197
