### ISSUE TITLE
Create two paths thru the prework, Mac and Ubuntu

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#18]
**From @h4w5:**

---

If possible, can we add a question at the beginning of the prework that determines if the student will be using a Mac or an Ubuntu machine? We can add the policy about not using Windows right there and a link to any suggested help.

We could also then insert images and commands in to the lessons that actually make sense for the given system as well.

**Comment by jessicaGA** [comment]
We will test asking PC students to use Git Bash so they can follow along during the navigating command line section.

**Comment by jeannyvaidya** [comment]
@h4w5 issue addressed with newly added [gitbash instructions](https://github.com/GA-WDI/fundamentals/pull/85). Will be included in next release later this week.
