### ISSUE TITLE
5.3.1 Exercise - Web Fonts

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#181]
The word "HTML" should be replaced with "CSS" in the sentence: "But you can also link to external fonts in your HTML." 

![5 3 1](https://cloud.githubusercontent.com/assets/12179055/19004738/3c278730-8725-11e6-85ee-1085bad47867.png)

**Comment by jshawl** [comment]
this should be html @kristynrb

**Comment by kristynrb** [comment]
@jshawl it doesn't make sense for "HTML" to be listed in both of those sentences.

**Comment by jshawl** [comment]
i think that sentence needs to be removed entirely

**Comment by jshawl** [comment]
pr open!
