### ISSUE TITLE
Student Feedback

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#183]
This issue contains recent bits of meaningful student feedback

**Comment by jshawl** [comment]
>Many of the prework materials had detrimental and debilitating typographical errors, illogical steps, and under-explained concepts. Generally speaking, a LOT of the materials need to be proofed before going out to students, as these errors seriously detract from the value of the learning materials in which they appear.

**Comment by jshawl** [comment]
>The pre-work was a little much without any help. I didn't complete it, but I felt the reinforcement of concepts through the program helped solidify what I did complete in the prework. Maybe implement a need to complete prework section by a certain date to keep people accountable.

**Comment by jshawl** [comment]
>[...] More Javascript in the prework

**Comment by cofauver** [comment]
"Now being 7 weeks in, I wish there would've been way more pre-work. I think maybe double or triple the amount of pre-work, and way more JavaScript based pre-work. What would've been helpful is solving basic functions, loops, algorithms, JavaScript logic, maybe even an intro to Ruby section. Instead of building the complex game with step-by-step instructions, as I did in the pre-work, I think smaller, foundational algorithm problems that will help you a grasp of JavaScript logic would've been most beneficial."

**Comment by cofauver** [comment]
![image](https://cloud.githubusercontent.com/assets/6520345/19048620/fa8f41bc-895b-11e6-933e-59bc6551c94a.png)

![image](https://cloud.githubusercontent.com/assets/6520345/19048646/19d13468-895c-11e6-9d84-3cd25b19c9b4.png)


* I don't have edit access on these surveys, so screenshots are easiest.

**Comment by ZebGirouard** [comment]
It is amazing that @cofauver got access to the Denver feedback results :-P

But yeah, sounds like SF and DEN are hearing the same issues from our fundamentals feedback.  Namely, that students feel underprepared.  Corey, are these from the 12-unit or old 6-unit pre-work?

As for the first comments, I'm between cohorts right now, so I would **love** to do a typo and error once-over, unless someone has already done that.

**Comment by mdang** [comment]
I just wanted to +1 the ideas of adding the ability to leave feedback within the site itself and to limit the scope of what it covers to emphasize the topics Andrew brought up in the Slack channel: 

Here’s what I’d like, can a student do the following:

```
1) create arrays
2) create objects
3) access elements from an array
4) access properties in an object
5) loop through an array
```

**Comment by amyealmeida** [comment]
Student Feedback from WDI Fundamentals across metros:

https://docs.google.com/document/d/1LrQZSP-ppkwd_ChZiHfzQgKxJe8FJuAYMT21eujjUYo/edit

**Comment by jnappy** [comment]
@mdang can you open another issue with that feedback? there's a lot in this issue unrelated to specific parts of the content and it's hard to find the constructive parts, but your bit about having students able to give feedback stands out

**Comment by microsarah** [comment]
All feedback in this issue has been added to the document Amy linked to above. This feedback helps fuel refreshing existing content & building new– so thank you for helping collect such valuable responses. We believe a lot of these frustrations will be resolved with our upcoming update of Fundamentals. 

After we launch, we'll discuss the best way to collect student feedback you receive outside the typeforms the students fill out.
