### ISSUE TITLE
1.2 Sublime Text Intro Video Fixes

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#185]
I only found one issue the first time through, but there may be more, and pretty sure this would require a reshoot or partial reshoot, so please add if you see others.

Narrator says, "Command or Control _backslash_ ()" allows you to comment code.  Unfortunately, only "Command or Control _slash_ (/)" works.

**Comment by microsarah** [comment]
This is documented in our HCD refresh docs @amyealmeida so I'm closing this out 👍
