### ISSUE TITLE
2 Intro to HTML Video Fixes

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#186]
I only found one issue the first time through, but there may be more, and pretty sure this would require a reshoot or partial reshoot, so please add if you see others.

Narrator says, "closing tags also contain a backslash".  Actually, that's a slash.

**Comment by jnappy** [comment]
@ZebGirouard it would probably require a reshoot to correct - do you know what video?

**Comment by ZebGirouard** [comment]
This guy: http://fundamentals.generalassemb.ly/02_chapter/intro.html

**Comment by microsarah** [comment]
We'll be reshooting these videos when we refresh our online HTML/CSS course. I made note of this in a larger QA document that tracks errors in these videos. Thanks for tagging this!
