### ISSUE TITLE
2.3 Quiz Confusing #3

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#189]
Why are we asking about CSS in this quiz?  We haven't even told students what it is yet.

**Comment by microsarah** [comment]
@jnappy Question 3 (first question in quiz)

**Comment by jnappy** [comment]
Agreed - thinking of replacing with questions around introductory HTML explanation or HTML boilerplate: 

option 1: "Which of the following best describes HTML?"
answer:  It is markup that provides the basic structure for any website; HTML tags tell the browser exactly what type of content or structure it is dealing with 

option 2: "Which of the following best describes HTML boilerplate?"
answer: A set of common structural elements to help us organize code 

@ZebGirouard  @microsarah @jshawl - thoughts?

**Comment by GA-MEB** [comment]
@jnappy Can we broaden this issue thread to include other problems with the quiz in 2.3? Or would you prefer we make separate issues for those?

**Comment by jshawl** [comment]
@GA-MEB prefer separate issues - easier to discuss / fix in isolation

**Comment by jnappy** [comment]
changed to what i outlined in option 1
