### ISSUE TITLE
3.9 Typos and Numbering Off

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#191]
- Bullet in 3) "Then, switch over to the some CSS." don't need "the"
- Numbers skip from 4) to 8)
- Not really sure what's going on with this: "Remember, if you still have CSS in our index.html when you changed the font color in the previous unit exercise. Go ahead move over this CSS from <style> into the style.css."  Sounds like we want "If you still have CSS in a <style> tag in the index.html file from a previous exercise, move this into style.css."

**Comment by andrewsunglaekim** [comment]
Not sure what's meant for your second bullet in this issue.  [PR here](https://github.com/GA-WDI/fundamentals/pull/202) for the other bullets, at least my stab on it.

**Comment by ZebGirouard** [comment]
Thanks @andrewsunglaekim , I cannot reproduce the second bullet anymore.  I blame gremlins.  So we should be all set once we pull your other two.

**Comment by microsarah** [comment]
We good on this one, gremlins?
