### ISSUE TITLE
4.4.1 Exercise Instructions Inaccurate

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#193]
In the beginning instructions, it says:

"As usual, don't forget to save your JSBin link."

This is the first time, we tell them to save their JSBin link, so we should either not say "As usual", or we should remind them every time...seems like removing "As usual" is the easier fix.

**Comment by ZebGirouard** [comment]
Continuing, when I click "Save" in JSBin, it takes me to a site with the JS Bin, it is blank, and it says "It looks like your last session crashed so I disabled Auto-Run JS for you"

It seems like it auto-saves on change, so do we even need to tell students this?

Can we get rid of that "Save" link at the top left of the JS Bin window altogether?

**Comment by microsarah** [comment]
This was resolved in fixing issue #197

**Comment by ZebGirouard** [comment]
Awesome, then sounds like we can close it as duplicate.
