### ISSUE TITLE
Short-term fixes for JS Bin

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#197]
Moving this to a new issue, because we could fix these things relatively quickly.

I've found this to be true, and unsure what exactly reproduces it. Pretty sure it is navigating away and back to a JS Bin exercise:

*Problem:* Instructions say to "type your answers directly into the text editor below", but there is not a text editor. There is a link to JS Bin, and I suppose that is what is meant, but it is still not clear to me where the JS Bin editor went.

*Solution:* This can be resolved by refreshing the page. Perhaps, we just need to add a note to refresh the page if they don't see a JS Bin editor?

**Comment by ZebGirouard** [comment]
Continuing with yet another issue, when I click "Save" in JSBin, it takes me to a site with the JS Bin, it is blank, and it says "It looks like your last session crashed so I disabled Auto-Run JS for you"

This is an issue in exercise 4.4.1 because it very clearly tells students to save. It seems like it auto-saves on change, so do we even need to tell students this?

**Comment by ZebGirouard** [comment]
It is unclear to me how I'm expected to get my old code from Unit 4 into the JS Bin in Unit 5.  I can go back to the Unit 4 screen, refresh the page (as I now know I have to do), then copy the HTML, then go back to Unit 5, refresh again, paste into HTML tab.  Then do the same with CSS...is this what we're expecting students to do?!  There must be an easier way, and we should indicate that in the instructions.

**Comment by microsarah** [comment]
@ZebGirouard re: last comment, think we should just create a bin with the code they need? Seems like the best option to me.

**Comment by ZebGirouard** [comment]
Yeah, I'm fine with that @microsarah

**Comment by ZebGirouard** [comment]
On exercise 5.4.1 we see this:

"As usual, don't forget to fork and save your JSBin link."

Now we have to fork it?  I think as you said, @microsarah , we should just provide them with the code they need, and get rid of any ask to fork and/or save.

**Comment by ZebGirouard** [comment]
And things like this should go away too (from 5.4.1):

"When you have your code from your previous exercise, follow the instructions below."

Strangely enough...my code actually persisted from the last exercise automatically this time.  The mysteries of JS Bin are beyond my comprehension.

**Comment by microsarah** [comment]
Yep I caught those @ZebGirouard thanks for the head's up. Can you 👀  my latest commit?

**Comment by microsarah** [comment]
lol yeah JS Bin is blowing my mind... in a bad way

**Comment by jshawl** [comment]
Pr seems to fix the above issues..
