### ISSUE TITLE
5.3.1 Confusing Instructions

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#199]
These are the instructions:

"You'll be using the code editor below. Copy and paste the code from the previous exercise in so that you have code to work with. As usual, don't forget to fork and save your JSBin link. You'll be reusing the code to continue building on the exercise in the next unit.

Take a look at the starter code in the editor below first."

If we're copying and pasting our code...and we don't have any starter code (it's just comments)...do we need that last sentence at all?

**Comment by microsarah** [comment]
This was fixed in #197
