### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#2]
Definitions of key vocabulary should be accessible outside of the 'cheat sheets'.

Imported from Fundamentals Spreadsheet.

Submitted by @phlco (copied from Gitlab)

**Comment by jeannyvaidya** [comment]
@phico will be added to 3.0 version that will be released at the end of this week.

**Comment by phico** [comment]
Wrong name, you mean @phlco ;)

**Comment by jeannyvaidya** [comment]
@phlco
