### ISSUE TITLE
Navigation is tricky on longer exercises

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#200]
The left and right arrow to take you to previous and next exercises, respectively, takes up almost the whole screen.  Unfortunately, if you're in JS Bin, it won't let you scroll the main page.  That means you need to click out of that box, but there's a 90% chance you're going to hit one of those massive arrows.  Is there a way we can make those smaller on exercise pages?

**Comment by jshawl** [comment]
@ZebGirouard can you link to one example?

**Comment by ZebGirouard** [comment]
@jshawl , yup.

1) Go here: http://fundamentals.generalassemb.ly/05_chapter/06_exercise.html
2) Open up the Output tab
3) Start typing in any of the other tabs
4) Try to scroll down to see the next step in the exercise

The problem is that the entire left and right, minus (I believe) the height of the top nav bar, is a button that goes to the previous or next page, and most of the middle is taken up by the JS Bin window.

**Comment by ZebGirouard** [comment]
Another example, @jshawl:

1) Go here: http://fundamentals.generalassemb.ly/09_chapter/06_quiz.html
2) Get to Question 4
3) Try to see option D

Similar problem, except now you can't scroll the quiz question even though it takes up more than a full screen.

**Comment by microsarah** [comment]
This issue will be remedied when we move the Fundamentals content to Learning platform (see #211  for more details) but because we're limited to Gitbook and JSBin tools, we're not able to fix this in the current version.
