### ISSUE TITLE
5.4.1 Instructions Unclear / Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#205]
I feel like we need a step between 2. and 3. that says something like "Add the `about` ID to the first div and the `services` ID to the second div."

Also this in 7. is missing the word "add": "So go ahead and a width of 46% and padding of 2%."

On 8. we are missing a word:
"Create an li, and give it a float of left."

That should say "Create an li *rule*"

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/244/files
