### ISSUE TITLE
Can someone undelete v3.0 branch?

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#206]
build step depends on it https://github.com/GA-WDI/fundamentals/blob/bb8c08d0c11c68296296eca8abca8635231eacca/.build.sh#L14-L32

otherwise all v3.0 links will 404

**Comment by jnappy** [comment]
@jshawl i didn't know that and was trying to clean up the repo last night...i don't have it locally, so i'll reach out to github

**Comment by jshawl** [comment]
uh oh

**Comment by jshawl** [comment]
if anyone pushes to this repo the v3.0 links will 404

**Comment by jshawl** [comment]
ok idea @jnappy we can just create a new 3.0 release off the current master branch

**Comment by jshawl** [comment]
the only update to v3.0 are updates to master anyway which is nothing but bugfixes

**Comment by jshawl** [comment]
problem solved https://github.com/GA-WDI/fundamentals/releases/tag/v3.0
