### ISSUE TITLE
5.4.1 Confusing Step

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#212]
"12 . Flip to your HTML, and wrap a new div, called "hero", around the main image.

Your img might freak out. Don't worry. It's because the "hero" div is grabbing the default div style written for your columns. Let's prevent that from happening. You need to counteract the div's width, margin, and display values."

For starters, that last sentence should be a step, not a note.  

Also, it should be much clearer.  We're counteracting it with the "hero" div rule, right?

Clarity is needed in that first sentence, too.  How do you *call* something "hero"...do we mean give it a "hero" class?

Any idea what good values would be for width, etc?  I don't think we need n00bz fiddling with pixel numbers for hours when they could spend that time learning more JS.

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/309/files
