### ISSUE TITLE
5.5 Question #6 misleading

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#213]
Question #6 with text "Which are the default states of the "float" property?" seems misleading.  The "default" state of the "float" property is "none".  Maybe replace "default" with "main"?

**Comment by jnappy** [comment]
updated

![image](https://cloud.githubusercontent.com/assets/7819607/19157483/74a6a266-8bb3-11e6-91f6-af3a77299bb5.png)
