### ISSUE TITLE
5.7 Typos and Misleading Steps

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#219]
#5 says this "5) Add a horizontal rule underneath after your closing paragraph tag."

We don't need both "underneath" and "after".

#6 says "Style your navbar by removing default stylings..."  I'm not sure what this "removing default stylings" is asking for.  Also, it is not necessary to make the Deliverable match the one at the bottom.

#11 is unnecessary, we already centered the text in these tags in the last assignment, plus there is no `header`.

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/244/files
