### ISSUE TITLE
Fundamentals Feedback link just goes to markdown file

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#220]
This link at the bottom of pages:

"How is your Fundamentals Experience going? Take a _quick survey_ to give us your feedback!"

...just takes you to a markdown file in plain text, and doesn't allow you to give any feedback.

**Comment by ZebGirouard** [comment]
@jshawl , can you take a look at this?

**Comment by jshawl** [comment]
@ZebGirouard what page is this?

**Comment by jshawl** [comment]
@microsarah this should not have been merged yet https://github.com/GA-WDI/fundamentals/pull/216 reverted

**Comment by microsarah** [comment]
@jshawl i have updated links for you– one typeform for each until. do you think it makes sense to put them on every page? what if a student (over the course of the same unit) thinks it's a different form and takes it twice? i don't think it'd be bad to have more feedback, just wondering your thoughts. also lmk the best way to give you these links

**Comment by jshawl** [comment]
oo i think this is ideal - I think every page is best  - increase the visibility! 

Is it possible to just have one form? will be much easier to manage

**Comment by jnappy** [comment]
agree with @jshawl - would be easier to have one form with a drop down asking for the unit #. This goes back on what I said earlier in the week - my bad!

cc: @jaytongsays

**Comment by microsarah** [comment]
FYI @jaytongsays already created separate links for each unit

**Comment by jshawl** [comment]
reasons to not work in a vacuum

**Comment by microsarah** [comment]
hey @jaytongsays @jnappy @jshawl just checking in on this

**Comment by jshawl** [comment]
one feedback form seems more maintainable, scalable, and results will be easier to group together or separate using a drop down.

Let's have one form for the entire fundamentals with the dropdown @jnappy mentions

**Comment by microsarah** [comment]
These links have been changed to "pulse checks" hosted on typeform.
