### ISSUE TITLE
6.2 Navigating the Command Line Unexplained URL

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#221]
This is a link for command line options toward the bottom of the lesson page:

http://catb.org/esr/writings/taoup/html/ch10s05.html#id2948149

Perhaps we should name this link something like [More information on command-line options](http://catb.org/esr/writings/taoup/html/ch10s05.html#id2948149)

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/313/files
