### ISSUE TITLE
6.4 Quiz Progress Confusing

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#222]
@jnappy 

So I've noticed this issue on other quizzes, but finally did an OK job of documenting it this time.  It seems like Quiz progress typically starts fast, then gets slower.  In this case, one question actually went backward.

Question 1 finished = 12%
Question 2 = 25%
Question 3 = 37%
4 = 50%
5 = 62%
6 = 75%
7 = 87%
**8 = 72%**
9 = 81%
10 = 90%
11 = 100%

Seems like, starting at question 8, that is proportionally the correct amount of progress per question.  Before that, it's too fast.

This issue seems to not be time-related.

**Comment by jnappy** [comment]
@ZebGirouard what about just changing the progress bar to question progress:

"7/15 completed!"

**Comment by ZebGirouard** [comment]
@jnappy , like that idea a lot!  I just want to make sure that's accurate, too, though.  If 11 changes to 15 at question #11, students will still be frustrated.

**Comment by jnappy** [comment]
Ok - figured it out..looks like there was an issue in the "path logic".  Just tested and working fine.

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368210/022a46f6-916d-11e6-929e-60e0c13ff51d.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368218/0e0abd20-916d-11e6-96ac-0f58c0f7be92.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368224/17b85242-916d-11e6-923e-26840f75bfd4.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368229/1dd75cf4-916d-11e6-950f-7ea76c287ef8.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368237/240a8006-916d-11e6-98b6-59e37842c4ee.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368242/29f8bcf8-916d-11e6-8327-b8ba7bc87b14.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368250/3098f0b4-916d-11e6-9b0e-54f0af17e589.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368265/3bc5c8b8-916d-11e6-85e6-087ddcb454de.png)

**Comment by jnappy** [comment]
![image](https://cloud.githubusercontent.com/assets/7819607/19368272/42cc071c-916d-11e6-8700-73dcda76b015.png)
