### ISSUE TITLE
7.2 GitHub Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#223]
- Three paragraphs after "Our GitHub Flow" heading we see this:

"Eventually, when you've made changes that you'd like to share with our team, you can *to* submit those changes back to us via our GitHub repo."

We can delete "to"

- A few lines down from the "2. Cloning" heading we see this:

"You can find the URL to clone on *right side* of the forked repo on GitHub:"

We should say "the right side"

- In the note right before "3 & 4. Editing and Committing"  we see this:

"If you're following along in Git Bash in Windows, the commands to *copy and past* are a little different"

It should say "paste"

**Comment by jnappy** [comment]
resolved here: https://github.com/GA-WDI/fundamentals/pull/275
