### ISSUE TITLE
Seems like assignments are out of order

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#224]
GitHub is Chapter 7 now, but it's talking about the Memory Game like we haven't started it yet.  I feel like the top paragraph's contents need to be split:

Assignment 2:

As you move through the next several chapters, you will be building parts of a browser-based Memory Game. Eventually, once all of the pieces are complete, your game will be turned in as your final assignment for WDI Fundamentals. Each chapter will introduce you to new tools and ideas, but it will be your job to figure out how to incorporate and use these tools to complete the assignment. 

Assignment 7:

In order to share our Memory Game publicly, and turn in the assignment, you will need to access code that is located on GitHub's servers. Follow the instructions below to get started!

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/314/files
