### ISSUE TITLE
8. Introduction to Javascript Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#228]
Underneath the JS Bin screenshot it says:

"As you can see in the screenshot above, JSBin features different window panes. On the right, with the light background, is the preview - this tool will display what your code builds in real time for you. It auto updated changes (unless you check off the ability to do so). On the left, with the dark background, is the editor. The editor allows us to write several instructions for our computer using HTML, CSS, and JavaScript; to execute these instructions, click the 'run with JS' in the right window.

To save your JS Bin session, just 'login' at the top. When you select 'File' and then 'New' you will be provided a blank space to work in. The moment you begin writing code, JS Bin will generate a URL that you can bookmark and come back to any time you want."

We should change that to:

"As you can see in the screenshot above, JSBin features different window panes. On the right, with the light background, is the preview - this tool will display what your code builds in real time for you. It *automatically* *updates* *on any change* (unless you check off the ability to do so). On the left, with the dark background, is the editor. The editor allows us to write several instructions for our computer using HTML, CSS, and JavaScript; to execute these instructions, click the *'Run with JS' button* in the right window.

To save your JS Bin session, just *select 'Login or Register'* at the top*, and log in with GitHub*. When you select 'File' and then 'New' you will be provided a blank space to work in. The moment you begin writing code, JS Bin will generate a URL that you can bookmark and come back to any time you want."

**Comment by jnappy** [comment]
see here: https://github.com/GA-WDI/fundamentals/pull/274
