### ISSUE TITLE
8.2.1 Instructions Wrong plus Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#232]
First, the easy one.  Because there is a "*Note*" in between numbers 1 and 2, the numbering starts over again, so we see:

"1. ..."
"1. ..."
"2. ..."

Now to the tricky one.  The first step says:

"You can test your answers by clicking the 'Run' button at the top of the page - it will spit out the evaluated result of your expression to the console."

This is **false**.  Completely untrue.  The only way to spit the result out is to wrap it in `console.log()`.  Do we want to explain that to the students?  Will take a couple more steps, but probably the best long-term fix.  If we don't explain to the students, we **must** say they should type in the "Console" tab and hit `enter`.

**Comment by ZebGirouard** [comment]
Still not sure how to assign, but I'm happy to take this one.  The second problem shows up again in 8.3.1, and perhaps others.

**Comment by ZebGirouard** [comment]
Yeah, 8.4.1 is very poorly worded as well and has logical errors like implying that "null" and "undefined" are the same thing.

**Comment by microsarah** [comment]
@ZebGirouard would you mind taking this one actually? I think you'd be better at wording here than I would. If not, let me know

**Comment by GA-MEB** [comment]
@ZebGirouard I know why that stuff about the 'Run' button is there -- it's content from back when we were using REPL.it (which _does_ have a big 'Run' button at the top of the page for running the code in the editor pane). That whole bit needs to be rewritten for JSBin (assuming we stick with it).

**Comment by ZebGirouard** [comment]
Thanks @GA-MEB .  Yeah, @microsarah , I'm happy to take it once I've gone through everything.  I believe this will require a few pull requests, and a full knowledge of all JS Units (8-11).  Not sure how to assign to myself, and wondering if that's a permissions issue.

**Comment by ZebGirouard** [comment]
Flagging 9.1.1 as having a similar issue.  I should just do a deep clean on all Exercises in Units 8-11.

**Comment by ZebGirouard** [comment]
Awesome, thanks.  Adding another flag for 10.1 having "Play" button in there.  This will be a big task.

**Comment by ZebGirouard** [comment]
10.4.1 also has this unnecessary step:

1. Go ahead an open up a new session in JSBin.

**Comment by ZebGirouard** [comment]
Continuing with flags...on 10.3.1

Let's get started! Some starter code has been provided in jsfiddle for this exercise.
Write the code to perform the actions listed below in the 'js' panel.
Click 'run' to see the results in the 'result' panel.

Neither 'js' nor 'result', nor really 'run' are a thing.

**Comment by ZebGirouard** [comment]
Same thing in 10.4.1

**Comment by ZebGirouard** [comment]
@jnappy , I have finished this work.

**Comment by jnappy** [comment]
see: https://github.com/GA-WDI/fundamentals/pull/379
