### ISSUE TITLE
8.3 Variables Instructions Unclear

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#233]
- Underneath the first "Test Yourself" heading it says:

"Assume that x is equal to 10. What values do the following expressions evaluate to? Check your answers in JS Bin."

Instead, maybe we should say:

"Assume that x is equal to 10. What values do the following expressions evaluate to? Save x as a variable in the JS Bin Console, and check your answers."

- Underneath the last "Test Yourself" heading it says:

"Give these a try – see if you can predict the final values of x, y, and z. Check your answers in JS Bin by copying the entire chunk of code into the editor window, running it, and then checking x,y, and z in the JS Bin terminal."

That last part should say "JS Bin *Console*"

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/315/files
