### ISSUE TITLE
8.4 Boolean Logic Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#234]
- Halfway down the "Undefined" section we see:

"Checking to see is a variable is undefined is important."

First "is" should be "if".

- Two problems in the last text in the "Undefined" section:

"We can also check for undefined using typeof()! This is because undefined is an Object that is immutable. If you'd like to learn more you should read [Mozilla's MDN entry for Undefined]."

What does being immutable have to do with it?  Maybe something more like "This is because undefined is a specific Object with its own data type."

Also we should see this for Mozilla: [Mozilla's MDN entry for Undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined)

- Second paragraph under "falsey / truthy" says:

"When this happens, the logical operators categorize their inputs as being either 'falsey' and 'truthy'."

"and" should be "or"

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/322
