### ISSUE TITLE
8.5 Quiz Still Has Frustrating String Matching

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#235]
String Matching not the best way to grade question #6.  I didn't put spaces between my +s, and it called it wrong.  Students (and I) would find this annoying.  Is there a better way?

Progress bar looks fine, 8-9% per question for 12-question quiz.

**Comment by jnappy** [comment]
I've seen this in chapter 11, too.  Definitely frustrating, but not something I will get to before transitioning.

**Comment by microsarah** [comment]
@GA-MEB here's the ticket for reference
