### ISSUE TITLE
8.6 Cheatsheet Disappointing Typo

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#236]
- Under "Special Cases" heading:

"When a variable is created, but is not assigned a value, it will be evaluated as null."

No, no, no!  We just explained the difference between `null` and `undefined` and now we're telling them the opposite.  The last word here should be `undefined`.

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/317/files
