### ISSUE TITLE
9.1 Conditionals Wonky Text Placement

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#237]
<img width="818" alt="screen shot 2016-10-06 at 12 28 00 pm" src="https://cloud.githubusercontent.com/assets/5480464/19165280/6b3e34f2-8bc0-11e6-9160-63aa54e64ef6.png">

**Comment by microsarah** [comment]
couldn't get it to do this. there's a `<br>` after the img– anything else i can try?

**Comment by ZebGirouard** [comment]
@microsarah 
Yeah, if screen size is smaller than the image, it won't do it.  You can assign it to me if you can't get anything to work, especially if you can't reproduce it.

**Comment by microsarah** [comment]
Can't seem to reproduce it. Thanks for taking this one @ZebGirouard!

**Comment by ZebGirouard** [comment]
This is fixed @jnappy, the problem was our old friend and enemy "float: left", we didn't clear that before the following paragraph.  Fixed this and a somewhat similar problem with "src: http://www.xkcd.com" link

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/379
