### ISSUE TITLE
Reevaluate time estimates for Fundamentals

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#238]
Maybe I'm mistaken, but I think we used to say that it took 60 hours to complete Fundamentals... and that was back before we added the HTML and CSS material. Now we say 40, which strikes me as really off. We should consider revising that estimate so that incoming students budget enough time to complete the work.

**Comment by jshawl** [comment]
Is there anyone we could ask in the company to take Fundamentals and tell us how long it takes?

**Comment by microsarah** [comment]
@jnappy can you weight in?

**Comment by microsarah** [comment]
This will be addressed in the upcoming refreshed version of Fundamentals.
