### ISSUE TITLE
9.1 Conditionals Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#239]
- Under first "Test Yourself" it says:

"Consider following conditional statement:"

We need a "the" in there.

- Under "Switch Statement" heading it says: 

"however, if we have a lot of conditions, the code *become* a bit repetitive and hard to read. "

Should say "becomes".

**Comment by jnappy** [comment]
addressed: https://github.com/GA-WDI/fundamentals/pull/318/files
