### ISSUE TITLE
5.3.1 link to jsbin

### ISSUE THREAD

**Issue by andrewsunglaekim** [GA-WDI/fundamentals#242]
intentionally empty?

**Comment by jshawl** [comment]
@andrewsunglaekim do you have the url?

**Comment by andrewsunglaekim** [comment]
http://jsbin.com/tifivo/embed?html,css,outputheight=600px

its the top link of the exercise in 5.3.1

**Comment by microsarah** [comment]
We added some language in case the embed wasn't showing up. It's under Instructions but maybe it's not obvious enough:
`If you don't see the JS Bin below, please refresh the page.`
