### ISSUE TITLE
backticks for all code type stuff

### ISSUE THREAD

**Issue by andrewsunglaekim** [GA-WDI/fundamentals#245]
Full disclosure these minor couple of PR's i've made is my first exposure to this new prework, but it seems like we could add significant readability to it if we just add backticks to everything code related. As i was reading through some of the chapter 5 exercises, it would really help readability if we labeled all html elements with backticks. `li` just reads better then li. It allows the student to see what parts of the walkthrough will match parts of the code they are writing

**Comment by jshawl** [comment]
👍 @andrewsunglaekim best way to get this merged is incremental progress

Start with a single page

**Comment by jnappy** [comment]
started here for chapters 1-3: https://github.com/GA-WDI/fundamentals/pull/310

**Comment by jnappy** [comment]
I'm going to remove the "Current Sprint" label - we'll need to come back to this one

**Comment by microsarah** [comment]
We've added this to the Fundamentals Styleguide for the upcoming update.
