### ISSUE TITLE
3.1 Clarify explanation of hexadecimal

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#251]
> In hex, they range from 0-9, then continue from A-F, with two characters each for red, green, and blue. 

^ Existing version
v My proposed re-write
 
> In a decimal (10) system, the values each digit can have run from 0 up to 9. In a hexadecimal (16) system, we use the letters A through F to extend that range; A is 10, B is 11, C is 12, and so on. For example, the number sixty-three is written in decimal as `63` (6 x 10 + 3 x 1); in hexadecimal, it's written as `3F` (3 x 16 + F x 1, where F is 15).
>
> Coming back to RGB, each pair of characters in an RGB hex code (e.g. `#46A529` -> `46`, `A5`, `29`) represents a color level between 0 (`00`) and 255 (`FF`) for red, green, or blue, respectively.

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/347/files
