### ISSUE TITLE
3.3 Classes and IDs are not selectors

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#252]
You can write selectors that select elements _by_ class or ID (e.g. `.some-class`, `#some-id`), but they are not themselves selectors.

**Comment by microsarah** [comment]
I'd argue you can call them selectors: https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors

**Comment by GA-MEB** [comment]
From that same article (emphasis mine): 
> In an HTML document, _CSS class selectors match an element_ based on the contents of the element's class attribute. The class attribute is defined as a space-separated list of items, and one of those items must match exactly the class name given in the selector.

A selector is just a pattern matcher.

**Comment by microsarah** [comment]
I would call them attributes in HTML, but selectors in CSS, yeh?

**Comment by jnappy** [comment]
+1 to @GA-MEB

**Comment by GA-MEB** [comment]
@microsarah Classes and IDs exist (and can be selected) independently of CSS -- not so with HTML. I would argue that a correct wording would be "CSS uses selectors to reference elements within an HTML file by their class and id attributes (and also sometimes by other attributes)."

**Comment by microsarah** [comment]
also fixed unit 5 lesson 7 which shares a paragraph about IDs from this lesson

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/376
