### ISSUE TITLE
3.4 Inaccurate explanation of relative vs absolute paths

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#253]
> Relative vs. Absolute Addressing: Relative addressing basically tells your browser: “Look in our project folder for the file specified. Or, if a folder is specified, look within that folder for the file specified.” On the other hand, when we link to a source outside of our project, it is referred to as an absolute address.

Not true. A relative address/path is one defined with respect to one's own position within a filesystem (e.g. `./index.html`, `main.css`); an absolute address/path is one defined with respect to some fixed location within a filesystem (like `/` or `~`) or to a fixed location on the world-wide web (which, one might argue, is itself a kind of giant file tree). 

A rule of thumb that we might want to share with students is that an absolute address always points to the same place, no matter where _you_ might happen to be.

**Comment by microsarah** [comment]
i think the goal here was to keep the language less technical and introduce the *concept* of relative vs absolute first. happy to add in changes, but we have to consider the students may not have grasped what a filesystem is quite yet. 

i like how you worded the rule of thumb for absolute tho– can you send over a full rewrite suggestion for the whole paragraph? @GA-MEB

**Comment by jnappy** [comment]
I'm with @GA-MEB - looks like this needs revising.

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/375
