### ISSUE TITLE
3.5 Content unclear

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#254]
> Your website can really come to life with a couple images! When you’d like to add images to your site, you should use the tag with the src attribute. src stands for “Source” and works just like the tag’s href attribute. 

I assume they're talking about `<img>` tags -- why don't they just say it? Also, `<img>` tags don't have an `href` attribute, just `src`.

**Comment by jnappy** [comment]
addressed here: https://github.com/GA-WDI/fundamentals/pull/319/files
