### ISSUE TITLE
3.6 Mistake in video content

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#255]
> "You have all the data in a plaintext file, but none of it's formatted"

The file shown onscreen when this is said is a Microsoft Word file, which is definitively _not_ plaintext.

**Comment by microsarah** [comment]
We'll be reshooting these videos when we refresh our online HTML/CSS course. I made note of this in a larger QA document that tracks errors in these videos. Thanks for tagging this!
