### ISSUE TITLE
3.7 Question 3 of Quiz was not taught.

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#256]
Just flagging this. If we expect students to Google for the answer, fine. But we should set that expectation up front.

For reference,
<img width="701" alt="screen shot 2016-10-06 at 6 07 11 pm" src="https://cloud.githubusercontent.com/assets/3653013/19172423/ca24d5fa-8bef-11e6-929b-7b908acfa2ba.png">

**Comment by jnappy** [comment]
Would it make sense to just point them to the MDN docs as a hint in the question?

https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

**Comment by jnappy** [comment]
Provided a hint in this question: 

![image](https://cloud.githubusercontent.com/assets/7819607/19422036/e4e669dc-93db-11e6-93c7-cad4408dba9a.png)
