### ISSUE TITLE
4.5 Quiz is only one question?

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#257]
That doesn't seem sufficient.

**Comment by jnappy** [comment]
Nope! Looks like you have to answer those questions to get to the next questions: 

![image](https://cloud.githubusercontent.com/assets/7819607/19173190/0e3f3718-8bf4-11e6-995d-de1ce317fb0f.png)

**Comment by GA-MEB** [comment]
Sorry, my bad!
