### ISSUE TITLE
6.1 Explanation of absolute/relative paths is redundant

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#259]
This topic was already mentioned in 3.4; maybe this explanation should go there?

See also: #253

**Comment by microsarah** [comment]
just saw this @GA-MEB. i guess they were trying to introduce the topic in 3.4 and fully explain it here. that flow makes sense to me but definitely want to hear your thoughts.

**Comment by microsarah** [comment]
@jnappy I updated 3.4's language but I think we should keep this lesson here. Your call on whether we should move this.

**Comment by jnappy** [comment]
@microsarah yeah, I'm not sure it would hurt to mention it again in more depth.  Going to close this one.
