### ISSUE TITLE
Should we be covering Git in Fundamentals?

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#26]
Per conversation with @coldhead we should evaluate the relative value of teaching Git in Fundamentals against the potential to unnecessarily confuse students with a complex topic they may not be ready for.

**Comment by jeannyvaidya** [comment]
It seems like students are fine with it (quiz results seem good). We're going to leave it for 3.0 release and track and assess student understanding closer moving forward.
