### ISSUE TITLE
[Suggestion] Have OS X students install Homebrew during Fundamentals

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#260]
At the moment, students install Git as part of Fundamentals, and then (often) reinstall it with Homebrew once the course begins. Including Homebrew in Fundamentals would mean that students would only have to install and configure Git once. It would also mean shorter installfests, and give students the ability to install other things with Homebrew, such as Atom (or even `node` or `nvm`).

I think it might be doable if we gave them step-by-step instructions, and/or offered limited support.

**Comment by microsarah** [comment]
This will be addressed in the upcoming refreshed version of Fundamentals.
