### ISSUE TITLE
[Suggestion] Introduce Git earlier, before HTML and CSS

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#261]
If students are working on files locally, rather than REPL.it, JSBin, or CodePen, we could have them practice their Git skills by having them use Git as they begin building sites. 

Since it makes sense to keep the Bash material together with the Git material, that would probably entail moving up both units.

**Comment by microsarah** [comment]
This will be addressed in the upcoming refreshed version of Fundamentals.
