### ISSUE TITLE
7.1 Don't encourage bad Git practices

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#263]
`git add .` is dangerous to use because you might accidentally add (and then commit) a sensitive file (like `.env`), or just something that you don't want to include in the repo (like images, `node_modules`, etc)

`git commit -m` encourages students to not write detailed commit messages.
I'm pretty sure that the only reason why this was done is so that students don't accidentally end up in Vim, but I think that risk could be mitigated in other ways.

In the very least, if we have to tell them to do these things, we should explain why they are not best practice.

**Comment by jnappy** [comment]
@GA-MEB i think you're last point is spot on.  `git add .` is an easy way to get started and getting into/out of Vim is petrifying the first time you encounter it.  

What do you think about adding a "warning" box? That's like, "Once you start class, you're going to learn some different ways to use the `git` commands, ways that are more inline with industry best practices.  But for now, just use `git add .` and `git commit -m` when versioning your code to make things easy."

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/396
