### ISSUE TITLE
7.4 Fix definition of `git diff`

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#264]
> git diff path/to/directory/or/file	       ||         Show the changes of the given file or directory.

Technically, it shows the _tracked but unstaged_ changes. It doesn't show the content of new untracked files. You can use `git diff` to see staged changes, but you need to use the `--staged` flag.

**Comment by microsarah** [comment]
Should we add in info about the `--staged` flag, or just change the description?

**Comment by jnappy** [comment]
Ignore the `--staged` flag

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/350/files
