### ISSUE TITLE
8.0 JSBin explanation in wrong place?

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#265]
> To start playing around with JavaScript, we'll be using a website called JS Bin.
> 
> As you can see in the screenshot above, JSBin features different window panes. On the right, with the light background, is the preview - this tool will display what your code builds in real time for you. It auto updated changes (unless you check off the ability to do so). On the left, with the dark background, is the editor. The editor allows us to write several instructions for our computer using HTML, CSS, and JavaScript; to execute these instructions, click the 'run with JS' in the right window.
> 
> To save your JS Bin session, just 'login' at the top. When you select 'File' and then 'New' you will be provided a blank space to work in. The moment you begin writing code, JS Bin will generate a URL that you can bookmark and come back to any time you want.
> 
> JS Bin has the ability to show a 'console'; this will display any JavaScript code that you need to run. You will need this from time to time. You can hide or display any tabs (HTML, CSS, JavaScript, or Console) by clicking on their tab to hide/show them as needed.

Haven't students already been using JSBin for a while by the time they get to unit 8? You know, for their HTML and CSS? I think the first two paragraphs of this explanation would be a lot more useful if they were given when JSBin was first introduced.

**Comment by jnappy** [comment]
Looks like they're introduced to it [here](http://fundamentals.generalassemb.ly/00_chapter/03_lesson.html).  

The explanation in unit 8 could probably be changed a bit: 

"To start playing around with JavaScript, we'll also be using JS Bin!"

Something like that? @GA-MEB

**Comment by jnappy** [comment]
Removing myself from this issue, as I won't be able to resolve before I transition.

**Comment by GA-MEB** [comment]
Sorry for dropping off the map, Jay. Yes, I think your suggestion is fine. We should also make sure that JSBin gets a nice clear introduction when it is introduced, which is why I suggested moving that content up.
