### ISSUE TITLE
[Suggestion][Meta] Reorder the JavaScript material

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#267]
The original plan for the JS material when v2 was about to be written was:
- variables
- expressions
- functions
- flow control (conditionals and loops) 
- arrays
- objects

This was nice because it emphasized evaluation and introduced functions as a kind of custom operator. These functions could then be made more sophisticated by adding in flow control. Finally, 
they'd learn about collections.

Although that ordering got rearranged during the development of the material, I think there was a lot of goodness in it, and I propose that we structure our JS material in a similar way.
1.  **Variables and expressions**. Emphasizing how evaluation works helps to make things like `x = x || 1` and `if (x)` more clear. I think the calculator analogy is still a good one. 
2.  **Defining and invoking functions** (maybe with a sub-section on using functions to break apart problems). Emphasize return values over side effects.
3.  **Conditional statements and loops**.
4.  **Objects**. Teach them as abstractions (i.e. collections of attributes) rather than simply as collections
5.  **Arrays**. introduce arrays as a specific type of object with certain properties. They'll have already seen square-brace syntax from the Objects unit. I think this would help with understanding certain array-like objects, such as `arguments` and the NodeLists that you get back when working with the DOM
6. **DOM**. Because it doesn't make sense to introduce the DOM before talking about Objects and Arrays. Do basic DOM manipulation -- changing `.innerHTML` and all that.
7. **Synthesis**. Tie it all together. Demonstrate how logic + DOM can equal an app.

I welcome any thoughts and feedback on this ordering -- it's something I've been sitting on for a little while, and wanted to bring out for discussion.

**Comment by microsarah** [comment]
This will be addressed in the upcoming refreshed version of Fundamentals.
