### ISSUE TITLE
8.3 Assignment operator should be introduced before it is used.

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#269]
That message box needs to be moved up.

**Comment by jnappy** [comment]
@GA-MEB see here: https://github.com/GA-WDI/fundamentals/pull/276

👍  or 👎

**Comment by GA-MEB** [comment]
👍 Reads much better. One small nit with the wording of the box; since we now say 'assignment operator' in the first paragraph, maybe change 

> HINT `=` is called the assignment operator

to 

> As mentioned above, `=` is called the assignment operator

**Comment by jnappy** [comment]
fixed!
