### ISSUE TITLE
Screenshot for RPS instructions is incorrect

### ISSUE THREAD

**Issue by elie** [GA-WDI/fundamentals#27]
Currently, https://github.com/ga-students/wdi-fundamentals-rps looks like this:

![screen shot 2015-04-21 at 12 04 26 pm](https://cloud.githubusercontent.com/assets/5502107/7260407/9e12c98e-e81e-11e4-8d92-6dd56e939344.png)

But the screenshot at http://fundamentals.generalassemb.ly/02_chapter/09_assessment.html looks like this

![image](https://cloud.githubusercontent.com/assets/5502107/7260356/4f38d182-e81e-11e4-8ba2-36428284e319.png)

The image should be updated, this is actually confusing students because what they see in the instructions is very different from what's in the actual repo.

**Comment by jeannyvaidya** [comment]
@elie thanks for the suggestion. Fixed and updated the screenshots.
