### ISSUE TITLE
[Suggestion] Consider rolling 8.4 into 8.2

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#270]
Rather than having them be their own section, put them in with the other types of values (Numbers, Strings, Booleans); they don't really need to be in a section all their own, and putting them in with the truthy/falsey stuff serves no purpose. 

Really, the truthy/falsey material could just be a footnote in the section on operators -- it doesn't need to be as prominent as it is. The most common times students will have to think about truthy/falsey behavior are testing for existence (`if (x)`) and having default values (`x = y || defaultValue`), and I'm not sure either of those cases are all that significant.

**Comment by microsarah** [comment]
This will be addressed in the upcoming refreshed version of Fundamentals.
