### ISSUE TITLE
8.5 Question 7 may be too tough -- tests material not covered

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#271]
Specifically, a student would need to know that comparison operators have higher precedence than equality operators, which I don't think is common knowledge for a new JS developer.

**Comment by jnappy** [comment]
Good point - do you think it's worth adding a footnote in the question or in one of the chapters?

**Comment by ZebGirouard** [comment]
@GA-MEB and @jnappy , I felt similarly about this question...unclear to me if we need to ask this question at all in fundamentals.  It's a great "teachable moment", but maybe we should just save it for Unit 1.

**Comment by jnappy** [comment]
Seems pretty straightforward, though, to mentioned.

**Comment by ZebGirouard** [comment]
@jnappy I don't follow.  The idea that comparison operators evaluate first and then that result would be used in an equality operation is not, if I remember correctly, explicitly stated in the lesson.  A better strategy, I believe, is to move this content from the quiz, and pose it as a thought question in one of the lessons or exercises.

This brings up a somewhat subtle confusion in assessments.  Are we trying to teach them new, useful things, or just assess what they should already know?  I think there's value in the former, but in a quiz or test with no instructor feedback, I think the latter is all we should hope to accomplish.  I would think the human response to any incorrect answer without an explanation grounded firmly in previous instruction will lead to frustration and blaming of the materials.

**Comment by jnappy** [comment]
i've updated the question: 

![image](https://cloud.githubusercontent.com/assets/7819607/19369209/0eef2730-9172-11e6-9654-147932fae04c.png)

will close this for now - IMO, this brief context is enough to answer the question.

**Comment by ZebGirouard** [comment]
Cool @jnappy . Yeah, if it is too hard, we'll hear about it in the feedback, but otherwise we're good.
