### ISSUE TITLE
wordage in 0.2

### ISSUE THREAD

**Issue by andrewsunglaekim** [GA-WDI/fundamentals#278]
`"Your instructional team will track your progress using our unit quizzes. "` This is not the case... at least not in DC? If that's the expectation, I have no idea, as an instructor, how to get access to my students fundamental quizzes. Can we change the verbage to be something more like  `"Your progress will be tracked using our unit quizzes"`

**Comment by andrewsunglaekim** [comment]
context, i'm running through materials to place back ticks where i think are appropriate:

a) for readability
b) get more familiar with prework as a whole
c) make an issue as neccessary

**Comment by jshawl** [comment]
`Your instructor will review your completed assignment on the first day of class.`

I don't think any market reviews day 1

**Comment by microsarah** [comment]
Fixed– FYI these updates are being made in a fork containing the new version of Fundamentals.
