### ISSUE TITLE
Note in 3.2 neccessary?

### ISSUE THREAD

**Issue by andrewsunglaekim** [GA-WDI/fundamentals#279]
This is a small point, but `Note: For servers that live behind a login, you'll need to add an "s" to the http—tricking our servers into thinking the font is a protected file.` is at the bottom of the file. 

When teaching anything, the idea is too not conflate. I don't know that this is explicitly necessary to use CSS and certainly isn't necessary for a beginner just starting out with the technology and may just stand to confuse. "Something else to think about" when they don't need to.

**Comment by jshawl** [comment]
also it's not tricking. anything served over https is secure - by definition

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/391/files
