### ISSUE TITLE
table formatting incorrect

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#288]
https://github.com/GA-WDI/fundamentals/blob/master/08_chapter/08_lesson.md

>| 'Falsey' | 'Truthy' | |- |- | | false | true | | 0 | All num

**Comment by microsarah** [comment]
I'm not sure how this should be formatted @jshawl

**Comment by jshawl** [comment]
![](https://dl.dropbox.com/s/ka5b27z0gepk1zi/Screenshot%202016-10-10%2013.37.17.png?dl=0)

should look like a table

**Comment by microsarah** [comment]
I know it should be a table @jshawl I don't know how the table should be divided, how many columns, what goes where, etc. Same with this part 
![screen shot 2016-10-12 at 12 18 35 pm](https://cloud.githubusercontent.com/assets/451523/19318271/0b0bdec6-9076-11e6-8937-0bddf65587fc.png)

**Comment by jshawl** [comment]
should look like ![](https://dl.dropbox.com/s/nvzm8z3rlrbw55u/Screenshot%202016-10-12%2015.52.28.png?dl=0)

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/394
