### ISSUE TITLE
"wherever you decided to put it"

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#289]
>wherever you've decided to put it

Let's recommend a place for students to put it https://github.com/GA-WDI/fundamentals/blob/master/08_chapter/12_assessment.md#getting-our-cards-in-order

**Comment by jnappy** [comment]
Referencing this PR: https://github.com/GA-WDI/fundamentals/pull/355/files

@jshawl I'm guessing you mean adding something about where in their filesystem it should be kept?
