### ISSUE TITLE
9.3 Quiz Issues

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#293]
- So here's an annoying problem, I can't scroll through this quiz at all.  Pretty sure I could with all the other ones.  It forces me to focus on a question, and I can't go back to old ones.  The worst part is that sometimes (most noticeably question 4) the question takes up more than a screen and you **need** to scroll.
- Progress looks good:
  Question 1 finished = 10%
  Question 2 = 20%
  Question 3 = 30%
  4 = 40%
  5 = 50%
  6 = 60%
  7 = 70% 
  8 = 80%
  9 = 90%
  10 = 100%

But...I answered 7/7 correctly...what??
- Question 7 asks:

"What statement can be used to exit a `loop`?" <- We never taught them this, no mention of 'break' whatsoever except in `switch/case`

**Comment by jnappy** [comment]
Should definitely add something about `break` statement in 9.2.

**Comment by ZebGirouard** [comment]
Adding on to the issue @nickandersonr 's issue:

'I answered every question right and when I clicked to see how I did, it “You answered 8/7 correctly.”'

**Comment by microsarah** [comment]
- I'm not having issues with the scroll and had a few others test on different browsers without difficulty. Unfortunately the height issue can't be resolved until we move away from gitbook later this year.
- I fixed the calculation error.
- I'll make sure we add 'break' into the next version's lessons– or replace the quiz question. Adding the 3.0 Release label to this issue so it stays on our radar.

**Comment by microsarah** [comment]
@GA-MEB
