### ISSUE TITLE
none of these are methods

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#299]
https://github.com/GA-WDI/fundamentals/blob/master/10_chapter/08_lesson.md#parentnode

previousSibling() – This will find the previous sibling of a selected element.
nextSibling() – This will find the next sibling of a selected element.
firstChild() – This will find the first child of a selected element.
lastChild() – This will find the last child of a selected element.

they are properties

**Comment by ZebGirouard** [comment]
Stupid question...why are they just properties?  Look like function calls to me.  "A JavaScript method is a property containing a function definition."  Is previousSibling not a function to find the previous sibling?

**Comment by jshawl** [comment]
@ZebGirouard type this in a console:

```js
document.body.previousSibling()

// and then

document.body.previousSibling
```

**Comment by ZebGirouard** [comment]
Gotcha @jshawl , makes sense now.  I shall make sure not to duplicate this when I see it today.

**Comment by jnappy** [comment]
see here: https://github.com/GA-WDI/fundamentals/pull/380
