### ISSUE TITLE
querySelector vs getElementsByTagName

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#303]
https://github.com/GA-WDI/fundamentals/blob/master/10_chapter/08_cheatsheet.md#traversing-the-dom

Hey so i noticed a pattern:

`document.getElementsByTagName('ul')[0]`

Instead, why not use `document.querySelector("ul")`

It will get the first element only

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/393
