### ISSUE TITLE
9.5 Exercise Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#311]
- At the top of the page, it says: "In Unit 8, we covered some game-changing concepts (pun intended). "  Do we mean Unit 9?

- Second para under Requirements heading, it says: "you would be displayed a popup from your browser that displays the sting 'Hello, friends'."  string, not sting

- In the Note about alert() it says: "Warning! Alerts are annoying *popup* that can be used to show a string of data to a user."  Should say popups.

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/362/files
