### ISSUE TITLE
10.1 Defining and Calling Functions Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#323]
- http://fundamentals.generalassemb.ly/10_chapter/02_lesson.html#defining-javascript-functions

Halfway down, we see:

"We'll focus on using function expression for these lessons. Let's look at an example:

Let's look at an example:
"

One too many `look at an example`s....

- http://fundamentals.generalassemb.ly/10_chapter/02_lesson.html#naming-functions

Incomplete camel-case description:

"To make it easier to read a name like nameofmyfunction, capitalize the first letter of each word (e.g. nameOfMyFunction – see the resemblance to a three-humped camel?)"

Should say: "To make it easier to read a name like nameofmyfunction, capitalize the first letter of each word after the first one (e.g. nameOfMyFunction – see the resemblance to a three-humped camel?)"

- http://fundamentals.generalassemb.ly/10_chapter/02_lesson.html#other-ways-to-define-your-functions

"Function expressions *is* only one way to define a function in JavaScript."

expressions *are*

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/363
