### ISSUE TITLE
10.2 Problem Solving with Functions Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#324]
- Second paragraph under "Determining if `o` has won"

"There's a principle we'll emphasize in this course – one that is so universally agreed upon **an** that it has a name. The principle is this: if you find yourself writing almost the exact same code in two places, take a moment to figure out how you can reorganize. We often refer to this concept as writing "DRY" code – with "DRY" standing for "Don't Repeat Yourself". In this case, we're considering writing two functions which would be exactly the same, except for that hard-coded value of 'x' vs 'o'. **Wouldn't it better** if we could make the function allThreeX more general so that it worked for both players?"

Get rid of "and", and change to "Wouldn't it be better"

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/364/files
