### ISSUE TITLE
10.2 Problem Solving with Functions JSBin Link Doesn't Work?

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#325]
I could be doing something wrong here, so here are my steps to repro:

1) Go here: http://fundamentals.generalassemb.ly/10_chapter/05_lesson.html#removing-the-duplicative-code
2) Click on the *this JSBin session* link toward the bottom of the page
3) Try to get things to show up in the Console

I couldn't.

**Comment by jaytongsays** [comment]
Clarifying issue here: The issue is that the JSBin link at the bottom of the page is showing Output window by default instead of Console.

Changing the URL address to have 'console' instead of 'output' should fix it: https://jsbin.com/cekezaz/edit?js,console

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/365
