### ISSUE TITLE
10.3 Accessing the DOM Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#326]
- Go here: http://fundamentals.generalassemb.ly/10_chapter/08_lesson.html#manipulating-the-dom

Scroll up a bit, and you'll see:

"`THis will return the parent of the first <li> element, which, in this case, is the <ul> element since it wraps all the <li elements.`"

That's a big H.  Also the second `<li>` is not closed.

**Comment by microsarah** [comment]
Fixed this under #297
