### ISSUE TITLE
10.4.1 Exercise Direction Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#328]
Go here: http://fundamentals.generalassemb.ly/10_chapter/11_exercise.html#instructions

- That first bullet has the wrong book.  "Me Talk Pretty One Day" should be "The Wind Up Bird Chronicle"

- What's up with those last two bullet items?  Seems like they just need a space between the asterisk and the text.

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/390
