### ISSUE TITLE
10.5 Quiz is...a mess

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#329]
Question 1 finished = 12%
Question 2 = 25%
Question 3 = 37%
4 = 50%
5 = 55% *that's weird*
6 = 66% *still weird*
7 = 77% *less weird now*
8 = 88%
9 = 90% *getting weird again*
10 = 90%
11 = 91% *what?*
12 = 92%
13 = 100% *why do we have a "bonus" question on a quiz? also, you cannot tab in this window...which is pretty important for writing multi-line functions. tab pushes you to the solution, which is pretty lame.*

I answered 8/11 correctly?! WTF?!  Pretty sure I got the thumbs up on all *12* questions that were supposedly graded.

Also kind of weird that I could only see 8 questions at the beginning of the quiz.  Like, I could scroll down and see Question #8, but not #9, #10, etc.  Until I finished #10, I could not see #11.  Same with #11 and #12

**Comment by jaytongsays** [comment]
Took a look in the Fundamentals Tracker as well and it seems like everyone who's gets all the questions right are only able to hit the 8/11 (73%) score mark.

**Comment by jnappy** [comment]
same issue here @ZebGirouard - looks like the "path logic" was a bit off on two questions.  Also, it should have been out of 10, not 11. 

![image](https://cloud.githubusercontent.com/assets/7819607/19368683/3f3ba6aa-916f-11e6-929e-040c89cf3535.png)
