### ISSUE TITLE
10.6 Cheat Sheet Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#330]
- First bullet on page:

"It can be _use_ both as an operator (accepting input values and calculating output values) and as a subroutine (do this thing... then do this thing...)."

"use" should be "used"
- Second bullet, first sub-bullet under "Best Practices for..."

"Keep you functions small - don't try to do too much in one step."

"you" should be "your"
- First bullet under here http://fundamentals.generalassemb.ly/10_chapter/08_cheatsheet.html#the-dom: 

"The Document Object Model (DOM) provides a structured representation of the HTML document and defines the way that structure can be _access_ from programs to update the structure, content and style."

"access" should be "accessed"

**Comment by microsarah** [comment]
This issue was resolved in a previous pull request that didn't reference the issue #.
