### ISSUE TITLE
10.7 Assignment Fixes

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#331]
...but arrays are in Unit 11, students don't know what they are, nor most likely what a key-value store is:

"document is a readily available JS object. (An object is basically an array that stores key-value pairs. Unlike regular arrays, the contents of an object are not ordered)."

Maybe more like: "document is a readily available JS object, with built-in properties and methods associated with it."

While we're in this space, it should not say "createElement is the method it comes with", but rather "createElement is a method it comes with".

And just below that:

"In this case, we passed createElement and argument of 'div'"

"and" should be "an"

And just below that:

"your browser's console to get see it in action."

Don't need "get"

**Comment by ZebGirouard** [comment]
And then there's this:

7 ) Create a function called createCards in your JavaScript file. This function will contain the code you just wrote to generate your cards.

8 ) Your createCards function should contain any JavaScript associated with the creation of the div elements with the class card.

Why is #8 just the second sentence of #7?

**Comment by microsarah** [comment]
fixed numbering as well

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/366
