### ISSUE TITLE
Change how functions are introduced in Unit 5

### ISSUE THREAD

**Issue by MattB-GA-Boston** [GA-WDI/fundamentals#34]
Introduce functions using function expressions (e.g. `var x = function() {...}`) instead of function declarations (`function x() {...}`). This makes it clear that functions are data, which is an important concept underlying many of the more complicated things students will be doing with functions, including :
- **methods** : Since functions are data, they can be stored as values inside objects.
- **callbacks** : Since functions are data, they can be passed in as arguments to other functions.
- **closure** : Since functions are data, they can be passed out of other functions as return values (and when they are passed out, they retain access to their original function scope).
- **IIFEs** : Since functions are data, `someFunction(3)` evaluates to `(function() {...})(3)`; the only reason we give functions names is so that we can reuse them, _just like any other kind of value_.

It also shouldn't require much of a change to the material to implement this.

**Comment by jessicaGA** [comment]
This is related to closed issue [36] (https://github.com/GA-WDI/fundamentals/issues/36).

**Comment by jessicaGA** [comment]
This is an issue of consistency. The content seems to jump between the syntax for function declaration (quiz vs content) without explaining the difference to students.

**Comment by jeannyvaidya** [comment]
@MattB-GA-Boston quizzes will be fixed to make sure the pre-work is using function expressions. Students will be introduced to function declarations, but primarily work with function expressions. Will be updated in the new 3.0 release later this week.
