### ISSUE TITLE
11.4 Quiz Bad String Matching Questions Again

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#342]
11a), 11b), and 11c) in the Unit 11 Quiz demands that we use dot notation...which was never taught as @jshawl points out in [his issue](https://github.com/GA-WDI/fundamentals/issues/308).

@jnappy , I think the best fix here might be to explicitly ask for dot notation in this question, and to actually teach it as "dot notation".

Ideally, we'd find a better way than string matching to test these questions, but at least dot notation has the fewest variables.  Longer-term, is it possible to accept multiple strings, or ignore white-space on typeform?

**Comment by jnappy** [comment]
this is causing issues with the the score reported on this quiz and it sounds like it will take some more time to work through it.

**Comment by jnappy** [comment]
Unfortunately, i can't get to this one before my transition.  I agree, though: should be a short explanation of dot notation and then update the quiz to ask for dot notation.
