### ISSUE TITLE
11.4 Quiz Weird Numbering and Side-effects

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#343]
Question 1 finished = 12%
Question 2 = 25%
Question 3 = 37%
4 = 50%
5 = 62% 
6 = 75%
7 = 87% 
8 = 61% *boooo*
9 = 69% 
10 = 76%
11a = 84% 
11b = 92%
11c = 100% 

Can only see through 8 at beginning of quiz, when finish #8, #9 through #11 show up

There is also this weird "infinite snap back effect".  Try this:

1) Scroll down to bottom of quiz after finishing #8
2) Try scrolling back up, slowly

The only way I can get back up to question #9 is to scroll really, really fast.

**Comment by jaytongsays** [comment]
Fundamentals Tracker showing average low scores across quiz submissions here.

**Comment by jnappy** [comment]
difficult to nail down the calculator logic here - not sure what the issue is, but i've fixed the progress tracker
