### ISSUE TITLE
Exercise Solutions - formatting for answers

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#345]
There are extra `  in 8.3.1 and 8.4.1 surrounding the solutions:

<img width="1160" alt="screen shot 2016-10-08 at 12 40 31 pm" src="https://cloud.githubusercontent.com/assets/12179055/19214552/9842f93e-8d54-11e6-83cd-5b094706a8d7.png">

**Comment by jnappy** [comment]
addressed: https://github.com/GA-WDI/fundamentals/pull/368/files
