### ISSUE TITLE
11.5.1 Exercise Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#346]
- Under requirements:

"Replace all your card variables Array types. "

I think that should just say: "Replace all your card variables with an `array` of cards."

- And then:

" one which will check if two *cars* are in play,"
should be:
" one which will check if two *cards* are in play,"

- On Step 3:

'You'll need to loop through the your cards **array** and then **Each** element should have an attribute that equals the card value (**i.e.** "queen").'

Should be:

'You'll need to loop through the your cards **array,** and then **each** element should have an attribute that equals the card value (**e.g.** "queen").'

**Comment by jnappy** [comment]
https://github.com/GA-WDI/fundamentals/pull/384
