### ISSUE TITLE
In Unit 6, introduce {} as 'object' instead of 'associative array'.

### ISSUE THREAD

**Issue by MattB-GA-Boston** [GA-WDI/fundamentals#35]
Calling objects 'associative arrays' ended up confusing our class a lot - they kept mixing up {} and []. 
I think it's totally possible for us to call them 'objects' without confusing students, so long as we don't mention any of the more advanced features of objects (e.g. methods, prototypes, constructors).

**Comment by jessicaGA** [comment]
@MattB-GA-Boston Introducing objects in Fundamentals is going to add another level of complexity that students aren't ready for at this stage of their learning. After reviewing with our Instructional Designer @jeannyvaidya we've decided to exclude objects from Fundamentals and instead spend the time covering HTML and CSS as per feedback we've received from instructors.
