### ISSUE TITLE
9.1 Paragraph and code pushed over to the right of flow charts

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#371]
![screen shot 2016-10-10 at 3 25 15 pm](https://cloud.githubusercontent.com/assets/12179055/19248410/dcc00b10-8efd-11e6-960f-5b1b1d58c86c.png)

**Comment by ZebGirouard** [comment]
@jnappy : Duplicated by #237 which I am submitting a PR for now.

**Comment by jnappy** [comment]
thanks @ZebGirouard 

@kristynrb see here: https://github.com/GA-WDI/fundamentals/pull/379
