### ISSUE TITLE
Consider re-appropriating some of the FEWD Git and Github content

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#39]
https://github.com/generalassembly-studio/FEWD_Curriculum/tree/master/Week_00_GitHub

**Comment by jeannyvaidya** [comment]
Most of FEWD material deals with github desktop client and does not cover git. Looked through to see what was missing in fundamentals and everything is mostly covered. Since we'll be adding a lot of new content to the 3.0 release, closing this issue for now. Fixing minor typos in github section.

**Comment by jeannyvaidya** [comment]
Change of plans: will be adding login section from FEWD to the next release.
