### ISSUE TITLE
href needs protocol

### ISSUE THREAD

**Issue by jshawl** [GA-WDI/fundamentals#398]
https://github.com/GA-WDI/fundamentals/blob/master/02_chapter/07_cheatsheet.md

![image](https://cloud.githubusercontent.com/assets/3824954/19389752/270b0f1a-91f3-11e6-9bb4-da76de6a5e53.png)

**Comment by microsarah** [comment]
Fixed– FYI these updates are being made in a fork containing the new version of Fundamentals.
