### ISSUE TITLE
Exercises need solutions

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#4]
The Ruby version contained solutions, but our JavaScript version doesn't.

Submitted by @phlco (copied from Gitlab)

**Comment by jdmaresco** [comment]
We will consider merging in a pull request that adds solutions for all of the exercises.

**Comment by jeannyvaidya** [comment]
@phlco we'll add solution code for the exercises in the next release.

**Comment by jeannyvaidya** [comment]
@phlco solutions added for Unit Exercises and HW assignments and students will have access. Will be updated for the new 3.0 release later this week.
