### ISSUE TITLE
3.7 Quiz #11 Confusing Answer

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#400]
Two problems with this quiz question:

1) Letter C option is poorly worded:

"Every class labelled "goodstuff" on the page will be styled with bold, green, size 14 font."

and is confusingly similar to correct answer (B):

" The HTML content with the class label "goodstuff" will be styled with bold, green, size 14 font."

We should probably re-word C to "**One HTML element with the class** "goodstuff" will be styled with bold, green, **and** size 14 font."

And re-word B to "**All** the HTML content with the class label "goodstuff" will be styled with bold, green, **and** size 14 font."

2) If you select C, it says some nonsense about IDs and # symbols.  We need to rewrite this to something more relevant.  Seems like this quiz explanation was just leftover from an old question.

**Comment by microsarah** [comment]
Fixed!
