### ISSUE TITLE
4.4.1 Missing Step and old Copyright

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#401]
- We should probably tell the students explicitly to remove the color red from the h1 rule in step 2.  Or maybe later.  But we should definitely not just ignore that there is already CSS in the JS Bin at the start, and forget to tell them to remove the red to make it look like the sample.
- We should also update the date in the footer. It says 2014.

**Comment by microsarah** [comment]
FYI these updates are being made in a fork containing the new version of Fundamentals
- removed the default CSS
- updated copyright date to 2017 in screenshots
