### ISSUE TITLE
10.7 Typo in callout box

### ISSUE THREAD

**Issue by kristynrb** [GA-WDI/fundamentals#405]
The last sentence in the callout box should read: 
 In order to find an element _that_ you want to append to, use JavaScript's document object to run either 'getElementById' or 'querySelector'.

![screen shot 2016-10-17 at 7 06 59 pm](https://cloud.githubusercontent.com/assets/12179055/19458888/0833a190-949d-11e6-91a8-125e4dfbcd11.png)

**Comment by microsarah** [comment]
This issue was fixed in a previous pull request that didn't reference the issue #.
