### ISSUE TITLE
Downloadable Videos or Transcripts?

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#421]
Is there a way for users to download videos or see video transcripts?  Some are having issues with the video player.

**Comment by microsarah** [comment]
Unfortunately users can't download videos but we may be able to provide transcripts. @amyealmeida let's discuss.

**Comment by microsarah** [comment]
We'll be providing transcripts for all video content when we move Fundamentals to the Learning Platform later this year.
