### ISSUE TITLE
v3.0 - Broken links to images

### ISSUE THREAD

**Issue by GA-MEB** [GA-WDI/fundamentals#442]
http://fundamentals.generalassemb.ly/06_chapter/02_lesson.html

http://fundamentals.generalassemb.ly/07_chapter/05_lesson.html

**Comment by microsarah** [comment]
also here: http://fundamentals.generalassemb.ly/07_chapter/intro.html

**Comment by GA-MEB** [comment]
Resolved. Closing this issue.
