### ISSUE TITLE
Introduce renaming files before 1.3.1

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#45]
Step 9 in [Exercise 1.3.1](http://fundamentals.generalassemb.ly/01_chapter/10_exercise.html) asks students to rename a file, but the concept has not been introduced. We should add that into the previous lesson.

**Comment by jeannyvaidya** [comment]
The relevant prompts will be moved to after the concept of moving and removing things is introduced. Will add hint to `mv` instead of rename. Updates will be in 3.0 release.
