### ISSUE TITLE
v3.1 4.2 Fonts and Texts Video mentions non-existent previous content

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#454]
I could be crazy, but the speaker in this video is mentioning a news bulletin we built in a previous unit, and I don't remember seeing that in a previous unit.

**Comment by ZebGirouard** [comment]
This seems to continue in the 4.3 and 4.4 video.  I don't recall making this News Bulletin.

**Comment by GA-MEB** [comment]
The News Bulletin ("New York Text News") is mentioned in the Sublime Text (2.3) video at about 3:03.
