### ISSUE TITLE
v3.1 6.5 Quiz Numbering is off

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#467]
Once I answer question 5 a bunch of other questions pop up, and my progress bar sets back to 50% (from 80%).  Not sure how to fix this.

**Comment by ZebGirouard** [comment]
This also happens after answering question 10 (question 11 appears).

**Comment by ZebGirouard** [comment]
Also happens after answering question 11 (question 12 appears).

**Comment by GA-MEB** [comment]
No longer an issue, since the latest version isn't using Typeform for quizzes.
