### ISSUE TITLE
Re-design the exercises in Unit 6

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#47]
The checkerboard exercises could be better-scaffolded. The instructions are probably a bit too technical. We should consider whether:

a) there's a better series of exercises
b) we can have this tie more into the overall project rather than be its own set of exercises

**Comment by jeannyvaidya** [comment]
newly designed [exercises](https://github.com/GA-WDI/fundamentals/pull/80) for unit 6: will be updated for the next 3.0 release later this week
