### ISSUE TITLE
Dot notation isn't covered in Unit 6

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#49]
But it is included in the Unit 6 quiz.

**Comment by jshawl** [comment]
Cannot see dot notation in quiz - https://ga-immersives.typeform.com/to/CCnUkk recommend closing this issue.

**Comment by jessicaGA** [comment]
Dot notation is included in quiz question number 4 (pop and push). However, we do cover both of those functions. I'm going to close this issue as it will not impact student learning.
