### ISSUE TITLE
As a student the ternary operator is more complex than if else

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#5]
From @RobAWilkinson – "a couple things seemed overly complicated to me however, it introduced ternary operators before it introduced if...else statements"

Original Gitlab discussion:

![](https://www.dropbox.com/s/y0zly51xo0rr0pv/Screenshot%202015-04-15%2010.14.24.png?dl=1)

**Comment by jessicaGA** [comment]
This is a duplicate issue see [53](https://github.com/GA-WDI/fundamentals/issues/53)
