### ISSUE TITLE
Clarification of '=' assignment operator | 3.2

### ISSUE THREAD

**Issue by amcooper** [GA-WDI/fundamentals#50]
@jdmaresco In section 3.2, it should be emphasized _very strongly_ that `=` denotes the assignment operator and not the condition of equality. I think this is confusing for beginners & the confusion is deepened by instructors' tendency to read `x = x + 1` as _x equals x plus one_. Suggestions:
* Include a big explanatory box right next to the one about _var_.
* Color `=` red (or magenta... something different from `===`) throughout the document.
* Try to get instructors to say _x is [re]assigned the value x plus one_.

**Comment by jnappy** [comment]
@amcooper added an larger explanation - thanks!
