### ISSUE TITLE
Loose equality | 3.1

### ISSUE THREAD

**Issue by amcooper** [GA-WDI/fundamentals#51]
@jdmaresco Section 3.1 includes a mention of the loose equality operator `==`. Beginners, I think, don't need it and can make do with strict equality `===`, and I think the same goes for JavaScript as a whole. A mention of `!==` belongs in there too.

**Comment by MattB-GA-Boston** [comment]
Bump.

I completely agree with this. In Boston, we tell students to never use loose equality - too much room for confusion. Let's start a habit of strict equality tests as early as possible.

**Comment by jeannyvaidya** [comment]
Fixed here: https://github.com/GA-WDI/fundamentals/pull/77. Closing.
