### ISSUE TITLE
Trade truth tables for conditional assignment | 3.3

### ISSUE THREAD

**Issue by amcooper** [GA-WDI/fundamentals#52]
@jdmaresco The conditional assignment material in Section 3.3 would be useful in class, but not necessarily in Fundamentals. Once you've learned _if-_ statements, things like `x = x || 10` can be handled fine by the beginner (`if ( x === null ) || ( x === undefined ) { x = 10; }`), if less efficiently. What _would_ be good here is the classic Boolean truth table, which I've always found helpful; I agree with my own teachers that these should be memorized. ![boolean_truth_table](https://cloud.githubusercontent.com/assets/2553540/9479500/9bda8bf8-4b4b-11e5-910d-8ab382cfa736.png)

**Comment by jeannyvaidya** [comment]
@sarahholden thanks! closing.
