### ISSUE TITLE
Ternary operator and switch statement | 4.1

### ISSUE THREAD

**Issue by amcooper** [GA-WDI/fundamentals#53]
@jdmaresco You can skip the ternary operator and the switch statement for beginners. _If-then-else_ is what they need to know.

**Comment by jessicaGA** [comment]
Totally agree. We will remove this in the next version (3.0) of Fundamentals.

**Comment by jeannyvaidya** [comment]
@amcooper Will move if-else to the top of the lesson as a primary focus for conditional statements. Ternary operator will be left out, but switch will remain for this 3.0 release, because a large part of Unit 5 relies on this knowledge. Will consider how to take out switch for a future release.
