### ISSUE TITLE
Pseudocode | 4.2

### ISSUE THREAD

**Issue by amcooper** [GA-WDI/fundamentals#54]
@jdmaresco It is fair to introduce the concept of pseudocode to the novice. It looks like it's introduced here sneakily & in a confusing way, in explanations of the _while_ and _for_ loops:
> Here's the general rule for how a while loop is written in JavaScript.
>
> `while (someCondition) {`
>   `  // A block of code.`
> `}`

[...]
>The general syntax for a for loop is
>
> `for (initialization; condition; finalExpression) {`
> `  // A block of code.`
> `}`

The pseudocode looks like it includes actual variables & could be confusing. Pseudocode should be explained & then styled differently, perhaps proportionally spaced and in two colors, one for pseudo (e.g. _some condition_) and another for actual code (e.g. _while_).

**Comment by jessicaGA** [comment]
We will introduce pseudocode in the "How To Think Like A Programmer" section. This will be updated in version 3.0.

**Comment by jeannyvaidya** [comment]
@amcooper New lesson and exercise added for pseudocode. 3.0 release later this week will include changes: https://github.com/GA-WDI/fundamentals/pull/80
