### ISSUE TITLE
Testing and 'testing' | 4.5

### ISSUE THREAD

**Issue by amcooper** [GA-WDI/fundamentals#55]
@jdmaresco This is a good place (or even back in 3.6) to introduce explicitly how to test your own code, i.e., including _console.log_ statements to display the values of variables and function returns & to confirm that they are what you intend them to be.
 
    console.log( 'Player: rock; Computer: paper; Winner: ' + getWinner( 'rock', 'paper' ) ); //testing
    [...]

This is particularly important due to the references to the Jasmine testing code included. That information should probably be a footnote if it's included at all.

**Comment by jeannyvaidya** [comment]
@amcooper New homework assignment: Memory Game added and will address this issue. Will be updated for the new 3.0 release.
