### ISSUE TITLE
Typos in Chapter 2

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#57]
from a student

### 2.1.1 Exercise

Step #5 references `git add` command. Should really be `git add .` with the period at the end, but terminal mentions it being incorrect.

### 2.4 Cheat Sheet

In the table, next to `git commit -m` "Commit message", "ommitted" should be "omitted." It's confusing because of misspelling and looks like it can be either committed or omitted.

**Comment by jeannyvaidya** [comment]
resolved and staged for commit

**Comment by jeannyvaidya** [comment]
resolved both typos
