### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cbas** [GA-WDI/fundamentals#64]
Under which license is the Fundamentals content published?

**Comment by jessicaGA** [comment]
Are you asking if you can reuse this material? If you want to use this material for GA purposes, that fine. However, the content can't be reused outside of GA.

**Comment by cbas** [comment]
@jessicaGA That's vague and the public repo is misleading. It should either be clearly as proprietary or otherwise tagged with a license identifier.
- https://spdx.org/licenses/
- https://creativecommons.org/licenses/

**Comment by jessicaGA** [comment]
I'll speak with GA's legal team and clarify.

**Comment by jessicaGA** [comment]
I brought this up to our legal team and we will add a creative commons license to this material in our next release (early Q2).

**Comment by jeannyvaidya** [comment]
@cbas @jessicaGA License will be included in global release in June with release of v3.0. See here: http://fundamentals.generalassemb.ly/v3.0/license.html
