### ISSUE TITLE
As a student `map` and `forEach` are overly advanced

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#7]
from @robawilkinson "I feel that map and forEach are pretty advanced I would have rather they just learned to iterate through arrays with a regular for loop"

Original Gitlab discussion:

![](https://www.dropbox.com/s/65kccu8ezdxyne4/Screenshot%202015-04-15%2010.22.39.png?dl=1)

**Comment by jeannyvaidya** [comment]
@robawikinson we'll leave out .map but add in a section about iterating with for loop.

**Comment by jeannyvaidya** [comment]
@robawilkinson these will be taken out of pre-work. Updates will be available in 3.0 release at the end of this week.
