### ISSUE TITLE
Should we start to incorporate ES2015 changes?

### ISSUE THREAD

**Issue by MattB-GA-Boston** [GA-WDI/fundamentals#72]
Although they aren't yet fully supported everywhere, ES2015 brings with it a number of significant changes to how JS should be written.
e.g.
-   `let` and `const` (block-scoped variants of `var`)
-   arrow functions (which, unlike normal functions, use a lexical `this`)
-   template strings (i.e. string interpolation in JS)
-   default parameter values

When and how should these changes be added into Fundamentals? Obviously, we don't want to introduce too much new material too quickly, but at the same time we also don't want them to develop bad habits that need to be corrected once the course begins.

**Comment by jeannyvaidya** [comment]
@MattB-GA-Boston thanks for your input here. This has been an ongoing conversation among the product team and instructors. We'll need to address whether or not we want to incorporate it in Baseline first and then make those changes in Fundamentals too. Do you teach Es6 to your students? If so, in which unit?

**Comment by MattB-GA-Boston** [comment]
@jeannyvaidya
Yes, we do - in fact, we teach it starting from day 1, by telling them to always use `let` and `const` instead of `var`. Template strings tend to get introduced mid-way through Unit 1. Arrow functions, for obvious reasons, don't get covered until after we've talked about `this` and context, which is usually in either late Unit 1 or early Unit 3.

**Comment by jeannyvaidya** [comment]
@MattB-GA-Boston thanks for input here. This is part of the larger conversation of moving the WDI Baseline curriculum to ES6 as well. I'm going to put this in the backlog for the next iteration for Fundamentals.
