### ISSUE TITLE
Improve title and introduction for chapter 3 / lesson 3

### ISSUE THREAD

**Issue by jdmaresco** [GA-WDI/fundamentals#8]
From @MattB-GA-Boston:  "A number of students got really thrown by that last lesson, and I think it had to do with contextualizing. Maybe giving it a better title and introduction would help?"

**Comment by code-for-coffee** [comment]
@MattB-GA-Boston are you referencing the **Boolean Logic** lesson?

**Comment by MattB-GA-Boston** [comment]
Yes. I know that section confuses a lot of students, and since the main thrust of that lesson isn't ordinary boolean logic, but rather the _edge cases_ - `null`, `undefined`, and truthy/falsey behavior - I think a clearer title and some better context in the introduction might improve understanding.

**Comment by code-for-coffee** [comment]
@MattB-GA-Boston I re-wrote part of it [here](https://github.com/ga-chicago/fundamentals/blob/boolean-logic-update/03_chapter/08_lesson.md).. do you think that helps? I submitted it as PR #67.

**Comment by MattB-GA-Boston** [comment]
@code-for-coffee 
Yes, I think that helps. I like the content that you've added. 

May I suggest a few additional changes?
* In the second bullet in the introduction:

  > Next, we will dive into **truthy** and **falsey** - the result of Javascript's attempt to _convert non-boolean values to booleans at runtime.

* In the section on `null`:

  > Null values are values that your decide have **no value**. But why would I want to do this? Why not use Undefined? As it turns out, we can't - variables in JavaScript are only `undefined` until they've been assigned a variable for the first time. `null` gives us a way to 'reset'  the value of a variable to nothing. 

  > Here's an example. Suppose you have an application for keeping track of your things. You might have  a string called `locationOfKeys` which indicates where your keys are. Then, one day, your keys get lost. What's the value of `locationOfKeys` now? Well, it's 'nothing' - they're lost. If `null` didn't exist, we would have to invent a special string value (perhaps `"lost"`) to signify that the keys are missing. `null` gives us a standard way of handling that kind of situation: allows us to just say `locationOfKeys = null;`

* Striking the section called `Evaluating Undefined and Null Values`, since it's now redundant.

* In the section on `truthy/falsey`:

  >  To be **falsey** means that boolean operators act in mostly the same way that they would if the value was `false`. For instance, using `!` (NOT) on a "falsey" value with evaluate to `true`, just as if you'd written `!false`. The "falsey" category of values includes: the number `0`, empty strings (`''`), `null`, and `undefined`. `false` is, of course, also "falsey".
> Being **truthy** is exactly the opposite of being falsey; using `!` (NOT) on a "truthy" value would evaluate to `false`. Anything that isn't "falsey" is "truthy", including all strings, all non-zero numbers, and (of course) `true`.
> As they say, "_to a hammer (read: boolean operator), everything looks like a nail (read: boolean value)_".
> Below are the exact rules that the boolean operators follow when dealing with non-boolean input values.
> ...

**Comment by code-for-coffee** [comment]
@MattB-GA-Boston - nice, I really like those changes. I'll add them and update my PR. Thanks for proofreading and providing feedback. I think the `locationOfKeys` is an example that all students can understand (vs the DDR reference).

**Comment by jeannyvaidya** [comment]
@MattB-GA-Boston and @code-for-coffee thanks for these changes! I've updated the lesson as per your updates.
